# -*- coding: utf-8 -*-
"""ETL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6qvyTNUUBtvYQGREuLPTG81qD15-lbB
"""

import pandas as pd
import sqlite3

print("1. Extraindo dados das planilhas...")
df_base = pd.read_excel("03_base_integrada.xlsx")
df_classificacao = pd.read_excel("03_classificacao_por_egresso.xlsx")
df_similaridade = pd.read_excel("03_similaridade_formacao_atuacao.xlsx")

print("2. Transformando e limpando os dados...")
# Garantindo que a Chave Primária (ID_ENTIDADE) seja texto (varchar) em todas as tabelas
# Isso evita erros de cruzamento (JOIN) no banco de dados
df_base['ID_ENTIDADE'] = df_base['ID_ENTIDADE'].astype(str).str.strip()
df_classificacao['ID_ENTIDADE'] = df_classificacao['ID_ENTIDADE'].astype(str).str.strip()
df_similaridade['ID_ENTIDADE'] = df_similaridade['ID_ENTIDADE'].astype(str).str.strip()

df_base.fillna(0, inplace=True)

print("3. Conectando ao Banco de Dados e realizando a Carga...")
# Cria um banco de dados relacional real chamado 'banco_egressos.db'
conn = sqlite3.connect('banco_egressos.db')

df_base.to_sql('base_integrada', conn, if_exists='replace', index=False)
df_classificacao.to_sql('classificacao_egresso', conn, if_exists='replace', index=False)
df_similaridade.to_sql('similaridade_formacao_atuacao', conn, if_exists='replace', index=False)

conn = sqlite3.connect('banco_egressos.db')

query = "SELECT * FROM classificacao_egresso LIMIT 5"
df_resultado = pd.read_sql_query(query, conn)

print("A consultar as primeiras 5 linhas da tabela no banco de dados:")
display(df_resultado)

conn.close()

print("Exportando tabelas finais para uso no Data Studio...")


df_base.to_csv("01_base_integrada_final.csv", index=False, encoding="utf-8-sig")
df_classificacao.to_csv("02_classificacao_final.csv", index=False, encoding="utf-8-sig")
df_similaridade.to_csv("03_similaridade_final.csv", index=False, encoding="utf-8-sig")