# -*- coding: utf-8 -*-
"""Agrupamento_area_conhecimento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ty1H7LVu5tPeaRxRHGknI8mwS-YgLrs

# Módulo II — Classificação temática automática com captura de produções e identifiação de

Este notebook implementa a etapa de classificação temática automática do RAGI considerando que, inicialmente, vocês podem ter apenas títulos das produções.
A finalidade é:

  - recuperar produções científicas dos egressos;
  enriquecer essas produções com metadados disponíveis em APIs;
  - classificar as produções por área do conhecimento;
  - estimar aderência aos 17 ODS da ONU;
  - consolidar os resultados por ID_ENTIDADE.

Fluxo desta etapa:

    TÍTULOS / ORCID / DOI
        ↓
    CAPTURA OPENALEX + CROSSREF
        ↓
    TEXTO DISPONÍVEL
    (título + temas + resumo, quando existir)
        ↓
    ZERO-SHOT
        ↓
    ÁREA + ODS
        ↓
    CONSOLIDAÇÃO POR ID_ENTIDADE

# 1. Configuração
Aqui instalamos as bibliotecas necessárias, montamos o Drive e definimos os parâmetros de captura.
"""

#============================================================
# 1. configuração e instalação
#============================================================
!pip install -q transformers sentence-transformers torch openpyxl requests rapidfuzz

from google.colab import drive
drive.mount('/content/drive')

import os
import re
import time
import unicodedata
import warnings
import requests
import numpy as np
import pandas as pd

from pathlib import Path
from urllib.parse import quote
from rapidfuzz import fuzz

warnings.filterwarnings('ignore')

# ============================================================
# PARÂMETROS IMPORTANTES
# ============================================================

# Coloque um e-mail para uso educacional das APIs
EMAIL_POLITE = 'vinicius_santos@discente.ufg.br'

BASE = Path('/content/drive/MyDrive/RAGI 2026 2')
PASTA_SAIDA = BASE / 'Modulo II' / 'Agrupamento por área de conhecimento e ODS'
PASTA_SAIDA.mkdir(parents=True, exist_ok=True)

# NÃO capturar todas as obras de cada egresso via ORCID.
# A análise usa SOMENTE os títulos que estão na planilha de egressos.
USAR_CAPTURA_POR_ORCID = False

# Enriquecer (buscar resumo/temas/ODS) somente os títulos-alvo da planilha
USAR_ENRIQUECIMENTO_POR_TITULO = True

# None = enriquece TODOS os títulos-alvo, sem limite
MAX_ENRIQUECIMENTO_POR_TITULO = None

# Estes dois parâmetros perdem o efeito agora
# (só seriam usados se você religar USAR_CAPTURA_POR_ORCID)
MAX_ENTIDADES = None
MAX_WORKS_POR_ENTIDADE = 100

print('Saída:', PASTA_SAIDA)

"""# 2. Localizar arquivos
O notebook procura a base integrada, a base de entidades e possíveis planilhas de títulos.
"""

#============================================================
# 2. localizar arquivos (versão corrigida)
#============================================================
def localizar_arquivo(padroes, raiz=BASE):
    for padrao in padroes:
        for caminho in raiz.rglob(padrao):
            if caminho.is_file():
                return caminho
    return None

def candidatos_fora_da_saida(padrao):
    """Lista arquivos do padrão, excluindo a pasta de saída e arquivos temporários."""
    return [
        p for p in BASE.rglob(padrao)
        if p.is_file()
        and not p.name.startswith('~$')
        and PASTA_SAIDA not in p.parents
    ]

ARQUIVO_BASE_INTEGRADA = localizar_arquivo(['*03_base_integrada*.xlsx'])
ARQUIVO_ENTIDADES = localizar_arquivo(['*01_entidades*.xlsx'])

# Se você souber o caminho exato da planilha de egressos com os títulos,
# informe aqui. Ex.: ARQUIVO_EGRESSOS_TITULOS = BASE / 'egressos.xlsx'
ARQUIVO_EGRESSOS_TITULOS = None

# Ordem de prioridade para achar os títulos-alvo:
CANDIDATOS_TITULOS = []

if ARQUIVO_EGRESSOS_TITULOS:
    CANDIDATOS_TITULOS.append(Path(ARQUIVO_EGRESSOS_TITULOS))

CANDIDATOS_TITULOS += candidatos_fora_da_saida('*egressos*.xlsx')
CANDIDATOS_TITULOS += candidatos_fora_da_saida('*openalex*.xlsx')
CANDIDATOS_TITULOS += candidatos_fora_da_saida('*crossref*.xlsx')
CANDIDATOS_TITULOS += candidatos_fora_da_saida('*titulos*.xlsx')
CANDIDATOS_TITULOS += candidatos_fora_da_saida('*publicacoes_titulos*.xlsx')

# remove duplicados mantendo a ordem de prioridade
CANDIDATOS_TITULOS = list(dict.fromkeys(CANDIDATOS_TITULOS))

print('Candidatos a planilha de títulos-alvo:')
for c in CANDIDATOS_TITULOS:
    print(' -', c.name)

"""# 3. Funções de normalização
Essas funções padronizam identificadores e textos para integração.

- Lattes vira apenas número;
- ORCID é normalizado com hífen;
- DOI é limpo;
- texto é normalizado para comparação.
"""

#============================================================
# 3. normalização
#============================================================
def limpar_valor(valor):
    if pd.isna(valor):
        return ''
    return str(valor).strip()

def remover_acentos(texto):
    texto = unicodedata.normalize('NFKD', texto)
    return ''.join(c for c in texto if not unicodedata.combining(c))

def normalizar_texto(valor):
    valor = limpar_valor(valor)
    if not valor:
        return ''
    valor = remover_acentos(valor)
    valor = valor.lower()
    valor = re.sub(r'[^a-z0-9\s]', ' ', valor)
    valor = re.sub(r'\s+', ' ', valor)
    return valor.strip()

def normalizar_lattes(valor):
    valor = limpar_valor(valor)
    return re.sub(r'\D', '', valor)

def normalizar_orcid(valor):
    valor = limpar_valor(valor)
    if not valor:
        return ''

    valor = re.sub(r'^https?://orcid\.org/', '', valor, flags=re.IGNORECASE)
    valor = re.sub(r'^orcid:\s*', '', valor, flags=re.IGNORECASE)
    valor = re.sub(r'\s+', '', valor)

    # Se vier sem hífens e tiver 16 caracteres, formata
    if len(valor) == 16 and valor.count('-') == 0:
        valor = '-'.join([valor[i:i+4] for i in range(0, 16, 4)])

    return valor.strip()

def normalizar_doi(valor):
    valor = limpar_valor(valor).lower()
    for prefixo in ['https://doi.org/', 'http://doi.org/', 'doi:']:
        valor = valor.replace(prefixo, '')
    return valor.strip().rstrip('/')

def localizar_coluna(df, alternativas):
    """
    Localiza colunas por nomes aproximados.
    """
    mapa = {normalizar_texto(c): c for c in df.columns}
    for alternativa in alternativas:
        chave = normalizar_texto(alternativa)
        if chave in mapa:
            return mapa[chave]
    return None

def combinar_campos_texto(df, colunas):
    """
    Combina várias colunas em uma única coluna textual.
    """
    if not colunas:
        return pd.Series([''] * len(df))

    def juntar(linha):
        valores = []
        for v in linha:
            v = str(v).strip()
            if v:
                valores.append(v)
        return '; '.join(dict.fromkeys(valores))

    return df[colunas].fillna('').apply(juntar, axis=1)

"""# 4. Dicionário dos ODS da ONU
Usamos os 17 ODS como rótulos para a classificação Zero-Shot.
"""

#============================================================
# 4. ODS da ONU
#============================================================
ODS_MAPA = {
    1: 'Erradicação da pobreza',
    2: 'Fome zero e agricultura sustentável',
    3: 'Saúde e bem-estar',
    4: 'Educação de qualidade',
    5: 'Igualdade de gênero',
    6: 'Água potável e saneamento',
    7: 'Energia limpa e acessível',
    8: 'Trabalho decente e crescimento econômico',
    9: 'Indústria, inovação e infraestrutura',
    10: 'Redução das desigualdades',
    11: 'Cidades e comunidades sustentáveis',
    12: 'Consumo e produção responsáveis',
    13: 'Ação contra a mudança global do clima',
    14: 'Vida na água',
    15: 'Vida terrestre',
    16: 'Paz, justiça e instituições eficazes',
    17: 'Parcerias e meios de implementação'
}

ODS_LABELS = list(ODS_MAPA.values())
ODS_NOME_PARA_CODIGO = {nome: codigo for codigo, nome in ODS_MAPA.items()}

def formatar_rotulo_ods(rotulo):
    codigo = ODS_NOME_PARA_CODIGO.get(rotulo)
    if codigo:
        return f'{codigo} {rotulo}'
    return rotulo

"""# 5. Funções de consulta às APIs
Etapa de captura.

O código consulta:

- OpenAlex por ORCID;
- Crossref por ORCID;
- OpenAlex por DOI;
- Crossref por DOI;
- OpenAlex por título;
- Crossref por título.

Quando a API devolve metadados, o código extrai:

- título;
- DOI;
- ano;
- resumo, quando existir;
- temas/conceitos/palavras-chave;
- periódico;
- ODS, no caso do OpenAlex.
"""

#============================================================
# 5. funções de API
#============================================================
def api_get_json(url, params=None, headers=None, timeout=45, tentativas=3):
    """
    Faz requisições com retry simples.
    """
    for tentativa in range(tentativas):
        try:
            resposta = requests.get(url, params=params, headers=headers, timeout=timeout)

            if resposta.status_code == 200:
                return resposta.json()

            if resposta.status_code in (429, 500, 502, 503, 504):
                time.sleep(2 * (tentativa + 1))
                continue

            return None

        except Exception:
            time.sleep(2 * (tentativa + 1))

    return None

def limpar_jats(texto):
    """
    Remove tags XML/JATS de resumos do Crossref.
    """
    if not texto:
        return ''
    texto = re.sub(r'<[^>]+>', ' ', str(texto))
    texto = re.sub(r'\s+', ' ', texto)
    return texto.strip()

def reconstruir_abstract_openalex(inverted_index):
    """
    O OpenAlex pode devolver resumo como índice invertido.
    Ex.: {'saúde': [0,5], 'pública': [1]}
    """
    if not inverted_index:
        return ''

    pares = []
    for palavra, posicoes in inverted_index.items():
        for pos in posicoes:
            pares.append((pos, palavra))

    pares.sort(key=lambda x: x[0])
    return ' '.join(palavra for _, palavra in pares)

def parse_openalex_work(work):
    """
    Converte um trabalho do OpenAlex em linha padronizada.
    """
    titulo = (work.get('title') or '').strip()
    doi = (work.get('doi') or '').strip()
    doi = doi.replace('https://doi.org/', '').replace('http://doi.org/', '')
    ano = work.get('publication_year', '')

    resumo = reconstruir_abstract_openalex(work.get('abstract_inverted_index'))

    temas = []

    # Topics
    for topic in (work.get('topics') or [])[:8]:
        if not isinstance(topic, dict):
            continue
        temas.append(topic.get('display_name', ''))
        temas.append((topic.get('subfield') or {}).get('display_name', ''))
        temas.append((topic.get('field') or {}).get('display_name', ''))
        temas.append((topic.get('domain') or {}).get('display_name', ''))

    # Concepts
    for concept in (work.get('concepts') or [])[:12]:
        if isinstance(concept, dict):
            temas.append(concept.get('display_name', ''))

    # Keywords
    for keyword in (work.get('keywords') or [])[:8]:
        if isinstance(keyword, dict):
            temas.append(keyword.get('display_name', ''))
        else:
            temas.append(str(keyword))

    temas = list(dict.fromkeys([t for t in temas if t]))[:50]

    # Periódico/fonte
    periodico = ''
    primary_location = work.get('primary_location') or {}
    source = primary_location.get('source') or {}
    if isinstance(source, dict):
        periodico = source.get('display_name', '')

    # ODS
    ods = []
    for goal in (work.get('sustainable_development_goals') or []):
        if not isinstance(goal, dict):
            continue

        url_goal = goal.get('id', '') or ''
        nome_goal = goal.get('display_name', '') or ''
        codigo = None

        m = re.search(r'/(\d+)$', url_goal)
        if m:
            codigo = m.group(1)

        if codigo and codigo.isdigit():
            nome_pt = ODS_MAPA.get(int(codigo), nome_goal)
            ods.append(f'{codigo} {nome_pt}'.strip())
        elif nome_goal:
            ods.append(nome_goal)

    ods = list(dict.fromkeys([o for o in ods if o]))

    return {
        'TITULO': titulo,
        'DOI': doi,
        'ANO': str(ano) if ano else '',
        'RESUMO': resumo,
        'TEMAS': '; '.join(temas),
        'PERIODICO': periodico,
        'ODS_OPENALEX': '; '.join(ods),
        'FONTE': 'OpenAlex API'
    }

def parse_crossref_item(item):
    """
    Converte um trabalho do Crossref em linha padronizada.
    """
    titulo = item.get('title', '')
    if isinstance(titulo, list):
        titulo = titulo[0] if titulo else ''
    titulo = str(titulo).strip()

    doi = item.get('DOI', '') or ''

    resumo = limpar_jats(item.get('abstract', ''))

    assuntos = item.get('subject', []) or []
    if isinstance(assuntos, str):
        assuntos = [assuntos]
    assuntos = [str(a).strip() for a in assuntos if str(a).strip()]

    periodico = item.get('container-title', '')
    if isinstance(periodico, list):
        periodico = periodico[0] if periodico else ''
    periodico = str(periodico).strip()

    issued = item.get('issued', {}) or {}
    date_parts = issued.get('date-parts', [[None]])
    ano = ''
    if date_parts and len(date_parts) > 0 and len(date_parts[0]) > 0:
        ano = date_parts[0][0] or ''

    return {
        'TITULO': titulo,
        'DOI': doi,
        'ANO': str(ano) if ano else '',
        'RESUMO': resumo,
        'TEMAS': '; '.join(dict.fromkeys(assuntos)),
        'PERIODICO': periodico,
        'ODS_OPENALEX': '',
        'FONTE': 'Crossref API'
    }

def openalex_por_orcid(orcid, max_works=100):
    """
    Busca produções no OpenAlex usando ORCID do autor.
    """
    if not orcid:
        return []

    producoes = []
    pagina = 1

    while len(producoes) < max_works:
        params = {
            'filter': f'author.orcid:{orcid}',
            'per-page': 100,
            'page': pagina,
            'mailto': EMAIL_POLITE
        }

        dados = api_get_json('https://api.openalex.org/works', params=params)
        if not dados:
            break

        resultados = dados.get('results', [])
        if not resultados:
            break

        for work in resultados:
            producoes.append(parse_openalex_work(work))
            if len(producoes) >= max_works:
                break

        if len(resultados) < 100:
            break

        pagina += 1
        time.sleep(0.4)

    return producoes

def crossref_por_orcid(orcid, max_works=100):
    """
    Busca produções no Crossref usando ORCID do autor.
    """
    if not orcid:
        return []

    headers = {
        'User-Agent': f'RAGI-UFG/1.0 (mailto:{EMAIL_POLITE})'
    }

    producoes = []
    offset = 0
    rows = 100

    while len(producoes) < max_works:
        params = {
            'filter': f'orcid:{orcid}',
            'rows': rows,
            'offset': offset,
            'select': 'DOI,title,abstract,subject,container-title,issued'
        }

        dados = api_get_json('https://api.crossref.org/works', params=params, headers=headers)

        if not dados or 'message' not in dados:
            break

        itens = dados['message'].get('items', [])
        if not itens:
            break

        for item in itens:
            producoes.append(parse_crossref_item(item))
            if len(producoes) >= max_works:
                break

        if len(itens) < rows:
            break

        offset += rows
        time.sleep(0.5)

    return producoes

def melhor_candidato(candidatos, titulo):
    """
    Escolhe o melhor resultado de busca por título.
    Só aceita se a similaridade for alta.
    """
    if not candidatos or not titulo:
        return None

    titulo_norm = normalizar_texto(titulo)
    melhor = None
    melhor_score = 0

    for candidato in candidatos:
        titulo_candidato = candidato.get('TITULO', '')
        titulo_candidato_norm = normalizar_texto(titulo_candidato)

        if not titulo_candidato_norm:
            continue

        score = fuzz.token_set_ratio(titulo_norm, titulo_candidato_norm)

        if score > melhor_score:
            melhor_score = score
            melhor = candidato

    if melhor_score >= 92:
        return melhor

    return None

def openalex_por_doi(doi):
    """
    Busca metadados no OpenAlex usando DOI.
    """
    if not doi:
        return None

    url = f'https://api.openalex.org/works/doi:{quote(doi, safe="")}'
    dados = api_get_json(url, params={'mailto': EMAIL_POLITE})

    if dados and isinstance(dados, dict) and dados.get('title'):
        return parse_openalex_work(dados)

    return None

def crossref_por_doi(doi):
    """
    Busca metadados no Crossref usando DOI.
    """
    if not doi:
        return None

    url = f'https://api.crossref.org/works/{quote(doi, safe="")}'
    headers = {
        'User-Agent': f'RAGI-UFG/1.0 (mailto:{EMAIL_POLITE})'
    }

    dados = api_get_json(url, headers=headers)

    if dados and 'message' in dados:
        return parse_crossref_item(dados['message'])

    return None

def openalex_por_titulo(titulo, top=5):
    """
    Busca produção no OpenAlex usando título.
    """
    if not titulo:
        return None

    params = {
        'search': titulo,
        'per-page': top,
        'mailto': EMAIL_POLITE
    }

    dados = api_get_json('https://api.openalex.org/works', params=params)
    if not dados:
        return None

    resultados = dados.get('results', [])
    candidatos = [parse_openalex_work(w) for w in resultados]

    return melhor_candidato(candidatos, titulo)

def crossref_por_titulo(titulo, top=5):
    """
    Busca produção no Crossref usando título.
    """
    if not titulo:
        return None

    headers = {
        'User-Agent': f'RAGI-UFG/1.0 (mailto:{EMAIL_POLITE})'
    }

    params = {
        'query.bibliographic': titulo,
        'rows': top,
        'select': 'DOI,title,abstract,subject,container-title,issued'
    }

    dados = api_get_json('https://api.crossref.org/works', params=params, headers=headers)

    if not dados or 'message' not in dados:
        return None

    itens = dados['message'].get('items', [])
    candidatos = [parse_crossref_item(item) for item in itens]

    return melhor_candidato(candidatos, titulo)

"""# 6. Carregar a base de entidades
A classificação não cria novas identidades. Ela usa o ID_ENTIDADE vindo da desambiguação.
"""

#============================================================
# 6. carregar entidades
#============================================================
if ARQUIVO_BASE_INTEGRADA:
    perfil_bruto = pd.read_excel(ARQUIVO_BASE_INTEGRADA)
    print('Usando 03_base_integrada.xlsx')
elif ARQUIVO_ENTIDADES:
    perfil_bruto = pd.read_excel(ARQUIVO_ENTIDADES)
    print('Usando 01_entidades.xlsx')
else:
    raise FileNotFoundError('Base de entidades não encontrada.')

COL_ENTIDADE = localizar_coluna(perfil_bruto, ['ID_ENTIDADE'])
COL_NOME = localizar_coluna(perfil_bruto, ['NOME_CANONICO', 'NOME_ORIGINAL', 'Discente', 'Nome'])
COL_LATTES = localizar_coluna(perfil_bruto, ['ID_LATTES_NORMALIZADO', 'ID_LATTES', 'ID_Lattes'])
COL_ORCID = localizar_coluna(perfil_bruto, ['ORCID_NORMALIZADO', 'ORCID'])

if not COL_ENTIDADE:
    raise ValueError('A coluna ID_ENTIDADE não foi encontrada na base.')

if not COL_NOME:
    perfil_bruto['NOME_TMP'] = ''
    COL_NOME = 'NOME_TMP'

if not COL_LATTES:
    perfil_bruto['LATTES_TMP'] = ''
    COL_LATTES = 'LATTES_TMP'

if not COL_ORCID:
    perfil_bruto['ORCID_TMP'] = ''
    COL_ORCID = 'ORCID_TMP'

entidades = perfil_bruto.groupby(COL_ENTIDADE, dropna=False).agg({
    COL_NOME: 'first',
    COL_LATTES: 'first',
    COL_ORCID: 'first'
}).reset_index()

entidades.columns = ['ID_ENTIDADE', 'NOME_CANONICO', 'ID_LATTES', 'ORCID']

entidades['ID_ENTIDADE'] = entidades['ID_ENTIDADE'].fillna('').astype(str)
entidades['CHAVE_LATTES'] = entidades['ID_LATTES'].apply(normalizar_lattes)
entidades['CHAVE_ORCID'] = entidades['ORCID'].apply(normalizar_orcid)

entidades = entidades[entidades['ID_ENTIDADE'].str.strip() != '']
entidades = entidades.drop_duplicates(subset=['ID_ENTIDADE'])

print('Entidades únicas:', len(entidades))
print('Entidades com ORCID:', (entidades['CHAVE_ORCID'] != '').sum())
display(entidades.head())

"""# 7. Carregar títulos existentes

Planilhas com informações já capturadas são aproveitadas
Somente publicações que tenham título são utilizadas. Se a planilha tiver apenas totais, sem título, ela será ignorada.
"""

#============================================================
# 7. carregar SOMENTE os títulos-alvo da planilha de egressos
#============================================================
def padronizar_publicacoes(df, fonte):
    if df is None or df.empty:
        return pd.DataFrame()

    col_titulo = localizar_coluna(df, [
        'TITULO', 'Titulo', 'Titulo_Trabalho', 'Titulo_Tese',
        'Titulo_Dissertacao', 'Titulo_do_Trabalho', 'title', 'Título',
        'Tese', 'Dissertacao', 'Trabalho',
        'Nome do Artigo', 'NOME_DO_ARTIGO'
    ])

    if not col_titulo:
        return pd.DataFrame()

    col_entidade = localizar_coluna(df, ['ID_ENTIDADE'])
    col_nome = localizar_coluna(df, ['NOME_CANONICO', 'Discente', 'Nome', 'NOME'])
    col_lattes = localizar_coluna(df, ['ID_Lattes', 'ID_LATTES', 'ID_LATTES_NORMALIZADO'])
    col_orcid = localizar_coluna(df, ['ORCID', 'ORCID_Egresso', 'ORCID_Lattes', 'ORCID_NORMALIZADO'])
    col_doi = localizar_coluna(df, ['DOI', 'doi'])
    col_ano = localizar_coluna(df, ['ANO', 'Ano', 'Year', 'Data_Publicacao', 'publication_year'])
    col_resumo = localizar_coluna(df, ['RESUMO', 'Resumo', 'Abstract', 'abstract'])
    col_periodico = localizar_coluna(df, ['PERIODICO', 'Periodico', 'container-title', 'Veiculo'])
    col_ods = localizar_coluna(df, ['ODS_ONU_Associados', 'ODS', 'SDG', 'ODS_OPENALEX'])

    out = pd.DataFrame()

    out['TITULO'] = df[col_titulo].fillna('').astype(str)
    out['ID_ENTIDADE'] = df[col_entidade].fillna('').astype(str) if col_entidade else ''
    out['NOME_CANONICO'] = df[col_nome].fillna('').astype(str) if col_nome else ''
    out['CHAVE_LATTES'] = df[col_lattes].apply(normalizar_lattes) if col_lattes else ''
    out['CHAVE_ORCID'] = df[col_orcid].apply(normalizar_orcid) if col_orcid else ''
    out['DOI'] = df[col_doi].fillna('').astype(str) if col_doi else ''
    out['ANO'] = df[col_ano].fillna('').astype(str) if col_ano else ''
    out['RESUMO'] = df[col_resumo].fillna('').astype(str) if col_resumo else ''
    out['PERIODICO'] = df[col_periodico].fillna('').astype(str) if col_periodico else ''
    out['ODS_OPENALEX'] = df[col_ods].fillna('').astype(str) if col_ods else ''

    col_temas = localizar_coluna(df, [
        'TEMAS',
        'Palavras_Chave_Conceitos',
        'Topico_Principal',
        'Subcampo_Conhecimento',
        'Campo_Conhecimento',
        'Grande_Area_Conhecimento'
    ])

    if col_temas:
        out['TEMAS'] = df[col_temas].fillna('').astype(str)
    else:
        campos_tematicos = [
            c for c in df.columns
            if any(chave in normalizar_texto(c) for chave in [
                'topico', 'subcampo', 'campo', 'grandearea',
                'palavrachave', 'conceito', 'ods', 'assunto', 'keyword'
            ])
        ]
        if campos_tematicos:
            out['TEMAS'] = combinar_campos_texto(df, campos_tematicos)
        else:
            out['TEMAS'] = ''

    out['FONTE'] = fonte
    out = out[out['TITULO'].fillna('').str.strip() != '']
    return out

producoes_fontes = []
arquivo_usado = None

for candidato in CANDIDATOS_TITULOS:
    try:
        df_tmp = pd.read_excel(candidato)
    except Exception as e:
        print('Erro ao ler', candidato.name, ':', e)
        continue

    pad = padronizar_publicacoes(df_tmp, f'Planilha: {candidato.name}')

    if not pad.empty:
        producoes_fontes.append(pad)
        arquivo_usado = candidato
        print('Títulos-alvo carregados de:', candidato.name, '| linhas:', len(pad))
        break   # <-- usa SOMENTE a primeira planilha que tiver títulos
    else:
        print('Sem coluna de título útil:', candidato.name)

if not producoes_fontes:
    print('ATENÇÃO: nenhuma planilha com títulos-alvo foi encontrada.')
    print('Se necessário, informe o caminho em ARQUIVO_EGRESSOS_TITULOS no bloco 2.')
else:
    print('Arquivo usado como fonte dos títulos-alvo:', arquivo_usado)

"""# 8. Capturar produções por ORCID
Esta é a parte principal da captura automática.
Para cada egresso que possui ORCID, o código busca produções no OpenAlex e no Crossref.
Isso ajuda a recuperar:

- título;
- DOI;
- resumo, quando existir;
- temas;
- ODS, no OpenAlex.
"""

#============================================================
# 8. captura por ORCID
#============================================================
producoes_api = []

if USAR_CAPTURA_POR_ORCID:
    entidades_com_orcid = entidades[entidades['CHAVE_ORCID'] != ''].copy()

    if MAX_ENTIDADES:
        entidades_com_orcid = entidades_com_orcid.head(MAX_ENTIDADES)

    print('Entidades que serão consultadas nas APIs:', len(entidades_com_orcid))

    for _, entidade in entidades_com_orcid.iterrows():
        orcid = entidade['CHAVE_ORCID']

        try:
            obras_openalex = openalex_por_orcid(orcid, MAX_WORKS_POR_ENTIDADE)
            obras_crossref = crossref_por_orcid(orcid, MAX_WORKS_POR_ENTIDADE)

            for obra in obras_openalex:
                obra['ID_ENTIDADE'] = entidade['ID_ENTIDADE']
                obra['NOME_CANONICO'] = entidade['NOME_CANONICO']
                obra['CHAVE_LATTES'] = entidade['CHAVE_LATTES']
                obra['CHAVE_ORCID'] = orcid

            for obra in obras_crossref:
                obra['ID_ENTIDADE'] = entidade['ID_ENTIDADE']
                obra['NOME_CANONICO'] = entidade['NOME_CANONICO']
                obra['CHAVE_LATTES'] = entidade['CHAVE_LATTES']
                obra['CHAVE_ORCID'] = orcid

            producoes_api.extend(obras_openalex)
            producoes_api.extend(obras_crossref)

            print(
                f"{entidade['ID_ENTIDADE']} | {entidade['NOME_CANONICO']} | "
                f"OpenAlex: {len(obras_openalex)} | Crossref: {len(obras_crossref)}"
            )

        except Exception as e:
            print('Erro na captura da entidade', entidade['ID_ENTIDADE'], e)

        time.sleep(0.7)

print('Produções capturadas via API:', len(producoes_api))

"""# 9. Consolidar e deduplicar produções
**Títulos existentes** e **produções capturadas por API** são juntadas.

É feita a deduplicação por DOI ou título normalizado.
"""

#============================================================
# 9. consolidação e deduplicação
#============================================================
COLUNAS_PRODUCAO = [
    'ID_ENTIDADE',
    'NOME_CANONICO',
    'CHAVE_LATTES',
    'CHAVE_ORCID',
    'TITULO',
    'DOI',
    'ANO',
    'RESUMO',
    'TEMAS',
    'PERIODICO',
    'ODS_OPENALEX',
    'FONTE'
]

todas_producoes = []

for df_fonte in producoes_fontes:
    if not df_fonte.empty:
        todas_producoes.append(df_fonte)

if producoes_api:
    todas_producoes.append(pd.DataFrame(producoes_api))

if todas_producoes:
    producoes = pd.concat(todas_producoes, ignore_index=True, sort=False)
else:
    producoes = pd.DataFrame(columns=COLUNAS_PRODUCAO)

for coluna in COLUNAS_PRODUCAO:
    if coluna not in producoes.columns:
        producoes[coluna] = ''

# Normaliza chaves
producoes['CHAVE_LATTES'] = producoes['CHAVE_LATTES'].apply(normalizar_lattes)
producoes['CHAVE_ORCID'] = producoes['CHAVE_ORCID'].apply(normalizar_orcid)

# Mapas de entidade
mapa_lattes = (
    entidades[entidades['CHAVE_LATTES'] != '']
    .drop_duplicates('CHAVE_LATTES')
    .set_index('CHAVE_LATTES')['ID_ENTIDADE']
    .to_dict()
)

mapa_orcid = (
    entidades[entidades['CHAVE_ORCID'] != '']
    .drop_duplicates('CHAVE_ORCID')
    .set_index('CHAVE_ORCID')['ID_ENTIDADE']
    .to_dict()
)

mapa_ent_nome = entidades.set_index('ID_ENTIDADE')['NOME_CANONICO'].to_dict()

def preencher_entidade(row):
    entidade = str(row.get('ID_ENTIDADE', '')).strip()
    if entidade:
        return entidade

    orcid = normalizar_orcid(row.get('CHAVE_ORCID', ''))
    if orcid and orcid in mapa_orcid:
        return mapa_orcid[orcid]

    lattes = normalizar_lattes(row.get('CHAVE_LATTES', ''))
    if lattes and lattes in mapa_lattes:
        return mapa_lattes[lattes]

    return ''

# fallback adicional: nome normalizado
# (caso a planilha de egressos não traga Lattes/ORCID)
mapa_nome_entidade = (
    entidades.assign(NOME_NORMALIZADO=entidades['NOME_CANONICO'].apply(normalizar_texto))
    [lambda d: d['NOME_NORMALIZADO'] != '']
    .drop_duplicates('NOME_NORMALIZADO')
    .set_index('NOME_NORMALIZADO')['ID_ENTIDADE']
    .to_dict()
)

def preencher_entidade_com_nome(row):
    entidade = preencher_entidade(row)
    if entidade:
        return entidade
    nome_norm = normalizar_texto(row.get('NOME_CANONICO', ''))
    return mapa_nome_entidade.get(nome_norm, '')

producoes['ID_ENTIDADE'] = producoes.apply(preencher_entidade_com_nome, axis=1)

producoes['NOME_CANONICO'] = producoes.apply(
    lambda r: r['NOME_CANONICO'] if str(r['NOME_CANONICO']).strip() else mapa_ent_nome.get(r['ID_ENTIDADE'], ''),
    axis=1
)

def preparar_chaves_producoes(df):
    df = df.copy()

    for coluna in COLUNAS_PRODUCAO:
        if coluna not in df.columns:
            df[coluna] = ''

    df['DOI_NORMALIZADO'] = df['DOI'].apply(normalizar_doi)
    df['TITULO_NORMALIZADO'] = df['TITULO'].apply(normalizar_texto)

    df['CHAVE_PUB'] = np.where(
        df['DOI_NORMALIZADO'] != '',
        'doi:' + df['DOI_NORMALIZADO'],
        'titulo:' + df['TITULO_NORMALIZADO']
    )

    df['SCORE_META'] = (
        df['TEMAS'].fillna('').astype(str).str.len() +
        df['RESUMO'].fillna('').astype(str).str.len() +
        df['ODS_OPENALEX'].fillna('').astype(str).str.len() +
        df['PERIODICO'].fillna('').astype(str).str.len() +
        df['DOI_NORMALIZADO'].fillna('').ne('').astype(int) * 500
    )

    return df

def deduplicar_producoes(df):
    if df.empty:
        return df.copy()

    df = preparar_chaves_producoes(df)
    df = df[df['TITULO_NORMALIZADO'] != '']

    if df.empty:
        return df

    df = df.sort_values(
        ['SCORE_META', 'FONTE'],
        ascending=[False, True]
    ).drop_duplicates('CHAVE_PUB').reset_index(drop=True)

    return df

producoes = deduplicar_producoes(producoes)

print('Produções únicas após deduplicação:', len(producoes))
display(producoes.head())

"""# 10. Enriquecer produções que estão só com título
Se a produção estiver sem resumo, sem temas e sem ODS, o código tenta buscar por:

- DOI, se existir;
- título, caso contrário.

Esse bloco é importante para casos em que há somente título.
"""

#============================================================
# 10. enriquecimento por DOI ou título (versão com progresso, cache e retomada)
#============================================================
import json as _json
from concurrent.futures import ThreadPoolExecutor, as_completed

USAR_PARALELO = True   # 4 consultas simultâneas; use False se preferir sequencial

# --- API mais rápida: timeout menor e menos retries (evita "silêncio" de minutos) ---
def api_get_json(url, params=None, headers=None, timeout=15, tentativas=2):
    for tentativa in range(tentativas):
        try:
            resposta = requests.get(url, params=params, headers=headers, timeout=timeout)
            if resposta.status_code == 200:
                return resposta.json()
            if resposta.status_code in (429, 500, 502, 503, 504):
                time.sleep(1.5 * (tentativa + 1))
                continue
            return None
        except Exception:
            time.sleep(1.5 * (tentativa + 1))
    return None

# --- cache em disco: não repete consultas e permite parar/retomar ---
ARQUIVO_CACHE = PASTA_SAIDA / 'cache_enriquecimento.json'
if ARQUIVO_CACHE.exists():
    with open(ARQUIVO_CACHE, 'r', encoding='utf-8') as f:
        cache_enriquecimento = _json.load(f)
else:
    cache_enriquecimento = {}

def salvar_cache():
    with open(ARQUIVO_CACHE, 'w', encoding='utf-8') as f:
        _json.dump(cache_enriquecimento, f, ensure_ascii=False)

def chave_cache(row):
    if row['DOI_NORMALIZADO']:
        return 'doi:' + row['DOI_NORMALIZADO']
    return 'titulo:' + row['TITULO_NORMALIZADO']

def enriquecer_um(tarefa):
    chave = tarefa['CHAVE_CACHE']
    if chave in cache_enriquecimento:
        return
    novo = None
    if tarefa['DOI_NORMALIZADO']:
        novo = openalex_por_doi(tarefa['DOI_NORMALIZADO']) or crossref_por_doi(tarefa['DOI_NORMALIZADO'])
    elif tarefa['TITULO']:
        novo = openalex_por_titulo(tarefa['TITULO']) or crossref_por_titulo(tarefa['TITULO'])
    cache_enriquecimento[chave] = novo if novo else {}

if USAR_ENRIQUECIMENTO_POR_TITULO and not producoes.empty:

    def precisa_enriquecer(row):
        return all(
            str(row.get(campo, '')).strip() == ''
            for campo in ['TEMAS', 'RESUMO', 'ODS_OPENALEX']
        )

    selecao = producoes[producoes.apply(precisa_enriquecer, axis=1)]
    if MAX_ENRIQUECIMENTO_POR_TITULO:
        selecao = selecao.head(MAX_ENRIQUECIMENTO_POR_TITULO)

    tarefas = [
        {
            'INDICE': i,
            'CHAVE_CACHE': chave_cache(row),
            'DOI_NORMALIZADO': row['DOI_NORMALIZADO'],
            'TITULO': row['TITULO'],
        }
        for i, row in selecao.iterrows()
    ]

    pendentes = [t for t in tarefas if t['CHAVE_CACHE'] not in cache_enriquecimento]
    print('Para enriquecer:', len(tarefas),
          '| já em cache:', len(tarefas) - len(pendentes),
          '| pendentes:', len(pendentes), flush=True)

    inicio = time.time()

    if USAR_PARALELO and pendentes:
        with ThreadPoolExecutor(max_workers=4) as pool:
            futuros = {pool.submit(enriquecer_um, t): t for t in pendentes}
            concluidos = 0
            for futuro in as_completed(futuros):
                futuro.result()
                concluidos += 1
                if concluidos % 20 == 0:
                    print(f'  progresso: {concluidos}/{len(pendentes)} | {time.time()-inicio:.0f}s', flush=True)
                    salvar_cache()
    else:
        for pos, tarefa in enumerate(pendentes, 1):
            enriquecer_um(tarefa)
            if pos % 10 == 0:
                print(f'  progresso: {pos}/{len(pendentes)} | {time.time()-inicio:.0f}s', flush=True)
                salvar_cache()

    salvar_cache()

    # --- aplica os resultados (do cache) na base de produções ---
    aplicados = 0
    for tarefa in tarefas:
        i = tarefa['INDICE']
        novo = cache_enriquecimento.get(tarefa['CHAVE_CACHE'], {})
        if not novo:
            continue
        for campo in ['DOI', 'ANO', 'RESUMO', 'TEMAS', 'PERIODICO', 'ODS_OPENALEX']:
            if novo.get(campo) and str(producoes.at[i, campo]).strip() == '':
                producoes.at[i, campo] = novo[campo]
                aplicados += 1

    print('Campos preenchidos pelo enriquecimento:', aplicados)
    print('Tempo total:', f'{time.time()-inicio:.0f}s')

    producoes = deduplicar_producoes(producoes)

print('Produções após enriquecimento:', len(producoes))

"""# 11. Montar o texto disponível para análise
Aqui é criado o texto que será enviado para o classificador.
Se só houver título, o modelo recebe só o título.
Se houver temas, resumo ou periódico, isso entra como contexto adicional.
"""

#============================================================
# 11. texto para análise
#============================================================
def montar_texto_analise(row):
    partes = []

    titulo = str(row.get('TITULO', '')).strip()
    if titulo:
        partes.append(titulo)

    temas = str(row.get('TEMAS', '')).strip()
    if temas:
        partes.append('temas: ' + temas[:500])

    resumo = str(row.get('RESUMO', '')).strip()
    if resumo:
        partes.append('resumo: ' + resumo[:800])

    periodico = str(row.get('PERIODICO', '')).strip()
    if periodico:
        partes.append('periódico: ' + periodico)

    texto = ' | '.join(partes)
    return texto[:2000]

producoes['TEXTO_ANALISE'] = producoes.apply(montar_texto_analise, axis=1)

df_classificacao = producoes.copy()

print('Exemplos de texto para análise:')
display(df_classificacao[['TITULO', 'TEXTO_ANALISE', 'ODS_OPENALEX']].head(10))

"""#12. Classificação Zero-Shot
Agora é utilizado um modelo multilíngue para classificar sem precisar de dados treinados.
Ele classifica área do conhecimento e ODS.

Para casos onde há somente títulos, também há uma coluna de confiança.
"""

#============================================================
# 12. classificação zero-shot
#============================================================
from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else -1

classificador = pipeline(
    'zero-shot-classification',
    model='MoritzLaurer/mDeBERTa-v3-base-mnli-xnli',
    device=device
)

AREAS_LABELS = [
    'Ciências Exatas e da Terra',
    'Ciências Biológicas',
    'Engenharias e Computação',
    'Ciências da Saúde',
    'Ciências Agrárias',
    'Ciências Sociais Aplicadas, Administração e Gestão da Informação',
    'Ciências Humanas e Educação',
    'Linguística, Letras e Artes',
    'Interdisciplinar'
]

def classificar_zeroshot(textos, labels, template, batch_size=8, multi_label=True):
    saidas = []

    for i in range(0, len(textos), batch_size):
        lote = [str(t)[:1000] for t in textos[i:i+batch_size]]

        if not lote:
            continue

        saida = classificador(
            lote,
            labels,
            multi_label=multi_label,
            hypothesis_template=template,
            truncation=True
        )

        if isinstance(saida, dict):
            saida = [saida]

        saidas.extend(saida)

    return saidas

# Inicializa colunas
for coluna in [
    'AREA_ZEROSHOT',
    'AREAS_SECUNDARIAS',
    'ODS_ZEROSHOT',
    'ODS_ADERENTES_ZEROSHOT'
]:
    df_classificacao[coluna] = ''

df_classificacao['AREA_SCORE'] = np.nan
df_classificacao['ODS_SCORE'] = np.nan

# Classifica apenas produções com título
mascara_titulo = df_classificacao['TITULO'].fillna('').astype(str).str.strip() != ''

if mascara_titulo.sum() > 0:

    textos = df_classificacao.loc[mascara_titulo, 'TEXTO_ANALISE'].fillna('').astype(str).tolist()
    textos = [t if t.strip() else 'sem informação' for t in textos]

    print('Classificando áreas do conhecimento...')
    resultados_areas = classificar_zeroshot(
        textos,
        AREAS_LABELS,
        'Este trabalho acadêmico pertence à área {}.'
    )

    df_classificacao.loc[mascara_titulo, 'AREA_ZEROSHOT'] = [
        r['labels'][0] for r in resultados_areas
    ]

    df_classificacao.loc[mascara_titulo, 'AREA_SCORE'] = [
        round(r['scores'][0], 4) for r in resultados_areas
    ]

    df_classificacao.loc[mascara_titulo, 'AREAS_SECUNDARIAS'] = [
        '; '.join(
            f'{label} ({score:.2f})'
            for label, score in zip(r['labels'], r['scores'])
            if score >= 0.30
        )
        for r in resultados_areas
    ]

    print('Classificando ODS...')
    resultados_ods = classificar_zeroshot(
        textos,
        ODS_LABELS,
        'Este trabalho acadêmico contribui para o objetivo de desenvolvimento sustentável {}.'
    )

    df_classificacao.loc[mascara_titulo, 'ODS_ZEROSHOT'] = [
        formatar_rotulo_ods(r['labels'][0]) for r in resultados_ods
    ]

    df_classificacao.loc[mascara_titulo, 'ODS_SCORE'] = [
        round(r['scores'][0], 4) for r in resultados_ods
    ]

    df_classificacao.loc[mascara_titulo, 'ODS_ADERENTES_ZEROSHOT'] = [
        '; '.join(
            formatar_rotulo_ods(label)
            for label, score in zip(r['labels'], r['scores'])
            if score >= 0.30
        )
        for r in resultados_ods
    ]

else:
    print('Não há produções com título para classificar.')

"""#13. Decisão final de ODS e área
- se o OpenAlex trouxe ODS, ele tende a ser priorizado;
- se não trouxe, usa Zero-Shot;
- área final usa Zero-Shot, mas os temas do OpenAlex ficam preservados para auditoria.
"""

#============================================================
# 13. decisão final
#============================================================
def decidir_ods(row):
    ods_openalex = str(row.get('ODS_OPENALEX', '')).strip()

    if ods_openalex:
        itens = [x.strip() for x in ods_openalex.split(';') if x.strip()]
        if itens:
            return pd.Series({
                'ODS_FINAL': itens[0],
                'ODS_SCORE_FINAL': 1.0,
                'ODS_FONTE': 'OpenAlex',
                'ODS_ADERENTES': '; '.join(itens)
            })

    ods_zs = row.get('ODS_ZEROSHOT', '')
    ods_zs = '' if pd.isna(ods_zs) else str(ods_zs)

    score_zs = row.get('ODS_SCORE', 0.0)
    score_zs = 0.0 if pd.isna(score_zs) else float(score_zs)

    aderentes_zs = row.get('ODS_ADERENTES_ZEROSHOT', '')
    aderentes_zs = '' if pd.isna(aderentes_zs) else str(aderentes_zs)

    return pd.Series({
        'ODS_FINAL': ods_zs,
        'ODS_SCORE_FINAL': score_zs,
        'ODS_FONTE': 'ZeroShot',
        'ODS_ADERENTES': aderentes_zs
    })

if not df_classificacao.empty:
    df_classificacao = pd.concat(
        [df_classificacao, df_classificacao.apply(decidir_ods, axis=1)],
        axis=1
    )
else:
    for coluna in ['ODS_FINAL', 'ODS_SCORE_FINAL', 'ODS_FONTE', 'ODS_ADERENTES']:
        df_classificacao[coluna] = ''

df_classificacao['AREA_FINAL'] = df_classificacao.get('AREA_ZEROSHOT', '')
df_classificacao['AREA_FONTE'] = 'ZeroShot'

def confianca_score(score, texto):
    try:
        score = float(score) if pd.notna(score) else 0.0
    except Exception:
        score = 0.0

    tamanho = len(str(texto))

    if score >= 0.65 and tamanho >= 120:
        return 'alta'
    if score >= 0.45:
        return 'media'
    return 'baixa'

df_classificacao['CONFIANCA_AREA'] = df_classificacao.apply(
    lambda r: confianca_score(r.get('AREA_SCORE', 0), r.get('TEXTO_ANALISE', '')),
    axis=1
)

def confianca_ods(row):
    if row.get('ODS_FONTE') == 'OpenAlex':
        return 'alta' if str(row.get('ODS_FINAL', '')).strip() else 'baixa'

    return confianca_score(
        row.get('ODS_SCORE_FINAL', 0),
        row.get('TEXTO_ANALISE', '')
    )

df_classificacao['CONFIANCA_ODS'] = df_classificacao.apply(confianca_ods, axis=1)

display(df_classificacao.head())

"""# 14. Consolidação por egresso
Agora são agregadas as produções por ID_ENTIDADE.
Isso permite responder coisas como:

- qual é a área predominante de cada egresso;
- quais ODS aparecem na produção dele;
- quantas publicações foram encontradas.
"""

#============================================================
# 14. consolidação por entidade
#============================================================
def moda_texto(serie):
    valores = serie.dropna().astype(str)
    valores = valores[valores.str.strip() != '']
    if valores.empty:
        return ''
    return valores.mode().iloc[0]

def primeiro_texto(serie):
    valores = [str(v).strip() for v in serie if str(v).strip() != '']
    return valores[0] if valores else ''

def unir_textos(serie):
    itens = set()
    for valor in serie:
        if pd.isna(valor):
            continue
        for parte in str(valor).split(';'):
            parte = parte.strip()
            if parte:
                itens.add(parte)
    return '; '.join(sorted(itens))

def titulos_exemplo(serie, n=10):
    vistos = []
    for valor in serie:
        valor = str(valor).strip()
        if valor and valor not in vistos:
            vistos.append(valor)
        if len(vistos) >= n:
            break
    return ' | '.join(vistos)

if not df_classificacao.empty:
    df_por_entidade = df_classificacao[
        df_classificacao['ID_ENTIDADE'].astype(str).str.strip() != ''
    ].copy()
else:
    df_por_entidade = pd.DataFrame()

if not df_por_entidade.empty:
    classificacao_egressos = df_por_entidade.groupby('ID_ENTIDADE').agg(
        NOME_CANONICO=('NOME_CANONICO', primeiro_texto),
        TOTAL_PUBLICACOES=('TITULO', 'count'),
        AREA_PREDOMINANTE=('AREA_FINAL', moda_texto),
        ODS_PREDOMINANTE=('ODS_FINAL', moda_texto),
        ODS_TODOS=('ODS_ADERENTES', unir_textos),
        TITULOS_EXEMPLO=('TITULO', lambda x: titulos_exemplo(x, 10))
    ).reset_index()
else:
    classificacao_egressos = pd.DataFrame(columns=[
        'ID_ENTIDADE',
        'NOME_CANONICO',
        'TOTAL_PUBLICACOES',
        'AREA_PREDOMINANTE',
        'ODS_PREDOMINANTE',
        'ODS_TODOS',
        'TITULOS_EXEMPLO'
    ])

print('Egressos com produção classificada:', len(classificacao_egressos))
display(classificacao_egressos.head())

"""# 15. Resumo de qualidade
Este bloco mostra quantas produções foram capturadas e quantas possuem metadados.
Isso é importante porque, com títulos curtos, a confiança da classificação depende muito da qualidade do texto disponível.
"""

#============================================================
# 15. resumo de qualidade
#============================================================
def contar_nao_vazio(df, coluna):
    if df.empty or coluna not in df.columns:
        return 0
    return int((df[coluna].fillna('').astype(str).str.strip() != '').sum())

resumo_qualidade = pd.DataFrame({
    'INDICADOR': [
        'Entidades carregadas',
        'Entidades com ORCID',
        'Produções únicas encontradas',
        'Produções com ID_ENTIDADE',
        'Produções com DOI',
        'Produções com resumo',
        'Produções com temas',
        'Produções com ODS vindo do OpenAlex',
        'Egressos com produção classificada'
    ],
    'QUANTIDADE': [
        len(entidades),
        int((entidades['CHAVE_ORCID'] != '').sum()),
        len(df_classificacao),
        contar_nao_vazio(df_classificacao, 'ID_ENTIDADE'),
        contar_nao_vazio(df_classificacao, 'DOI_NORMALIZADO'),
        contar_nao_vazio(df_classificacao, 'RESUMO'),
        contar_nao_vazio(df_classificacao, 'TEMAS'),
        contar_nao_vazio(df_classificacao, 'ODS_OPENALEX'),
        len(classificacao_egressos)
    ]
})

display(resumo_qualidade)

"""# 16. Validação humana
Para apenas títulos, a validação humana é importante.
Este arquivo serve para revisar manualmente as classificações.
"""

#============================================================
# 16. validação humana
#============================================================
if not df_classificacao.empty:
    validacao = df_classificacao[[
        'ID_ENTIDADE',
        'NOME_CANONICO',
        'TITULO',
        'AREA_FINAL',
        'AREA_SCORE',
        'CONFIANCA_AREA',
        'ODS_FINAL',
        'ODS_SCORE_FINAL',
        'ODS_FONTE',
        'CONFIANCA_ODS',
        'TEXTO_ANALISE'
    ]].copy()
else:
    validacao = pd.DataFrame(columns=[
        'ID_ENTIDADE',
        'NOME_CANONICO',
        'TITULO',
        'AREA_FINAL',
        'AREA_SCORE',
        'CONFIANCA_AREA',
        'ODS_FINAL',
        'ODS_SCORE_FINAL',
        'ODS_FONTE',
        'CONFIANCA_ODS',
        'TEXTO_ANALISE'
    ])

validacao['AVALIACAO_HUMANA'] = ''
validacao['JUSTIFICATIVA'] = ''
validacao['OBSERVACAO'] = ''

display(validacao.head())

"""# 17. Exportar resultados
O módulo salva os arquivos principais para uso posterior no projeto e no dashboard.
"""

#============================================================
# 17. exportação
#============================================================
def truncar_texto(valor, limite=30000):
    if pd.isna(valor):
        return ''
    return str(valor)[:limite]

def preparar_para_excel(df):
    df = df.copy()
    for coluna in df.columns:
        if df[coluna].dtype == 'object':
            df[coluna] = df[coluna].map(lambda x: truncar_texto(x))
    return df

ARQUIVO_PRODUÇÕES = PASTA_SAIDA / '01_producoes_capturadas.xlsx'
ARQUIVO_CLASSIFICADAS = PASTA_SAIDA / '02_producoes_classificadas.xlsx'
ARQUIVO_EGRESSOS = PASTA_SAIDA / '03_classificacao_por_egresso.xlsx'
ARQUIVO_VALIDACAO = PASTA_SAIDA / '04_validacao_humana.xlsx'
ARQUIVO_RESUMO = PASTA_SAIDA / '05_resumo_qualidade.xlsx'

preparar_para_excel(producoes).to_excel(ARQUIVO_PRODUÇÕES, index=False)
preparar_para_excel(df_classificacao).to_excel(ARQUIVO_CLASSIFICADAS, index=False)
preparar_para_excel(classificacao_egressos).to_excel(ARQUIVO_EGRESSOS, index=False)
preparar_para_excel(validacao).to_excel(ARQUIVO_VALIDACAO, index=False)
resumo_qualidade.to_excel(ARQUIVO_RESUMO, index=False)

print('Arquivos salvos em:')
print(PASTA_SAIDA)