# -*- coding: utf-8 -*-
"""analise_similaridade_formacao_atuacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_HvFQh-QyWQWQtkPbCh8k0ise0ET7UH

# Módulo II — Similaridade Semântica

## Formação acadêmica e atuação profissional

### Objetivo

Este notebook implementa a etapa de **similaridade semântica**.

A etapa anterior, **Normalização e Desambiguação de Entidades**, estabeleceu o `ID_ENTIDADE` como identificador lógico de cada egresso.

Neste módulo, essa identificação será reutilizada para construir dois documentos por egresso:

- **Documento de Formação**;
- **Documento de Atuação Profissional**.

A partir desses documentos, serão gerados embeddings e calculada a similaridade semântica entre formação e atuação.

## 1. Estrutura das relações

O modelo adotado neste notebook mantém a mesma lógica do módulo anterior:

```text
ENTIDADE
   │
   ├── Lattes
   ├── OpenAlex
   └── Crossref
          │
          ↓
    ID_ENTIDADE
          │
          ├── Documento de Formação
          │
          └── Documento de Atuação
                    ↓
          Similaridade Semântica
```

O objetivo não é criar novamente a identidade do egresso.

O `ID_ENTIDADE` já produzido pelo módulo anterior será a chave de integração desta etapa.

## 2. Importação das bibliotecas

As bibliotecas abaixo serão utilizadas para:

- leitura e escrita das planilhas;
- leitura dos currículos Lattes em XML;
- organização dos dados;
- geração dos embeddings;
- cálculo da similaridade do cosseno.
"""

from google.colab import drive
drive.mount("/content/drive")

!pip -q install pandas openpyxl numpy scikit-learn sentence-transformers tqdm lxml

import os
import re
import glob
import numpy as np
import pandas as pd

from pathlib import Path
from lxml import etree
from tqdm.auto import tqdm
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 200)

"""## 3. Definição dos arquivos de entrada e saída

A estrutura de pastas segue a organização utilizada no notebook de **Normalização e Desambiguação de Entidades**.

As bases de OpenAlex e Crossref continuam sendo lidas a partir das pastas `Estratégia 1`.

A base `03_base_integrada.xlsx` e a base `01_entidades.xlsx` são utilizadas como resultado da etapa anterior.

Os currículos Lattes continuam sendo obtidos da pasta de XMLs estruturados.
"""

# pasta onde estão as bases utilizadas pelo projeto
PASTA_BASE = Path("/content/drive/MyDrive/RAGI 2026 2")

# arquivos produzidos pelo módulo de desambiguação
PASTA_DESAMBIGUACAO = PASTA_BASE / "Modulo II" / "Desambiguação de entidades"

ARQUIVO_ENTIDADES = PASTA_DESAMBIGUACAO / "01_entidades.xlsx"
ARQUIVO_BASE_INTEGRADA = PASTA_DESAMBIGUACAO / "03_base_integrada.xlsx"

# currículos Lattes estruturados
PASTA_LATTES = (
    PASTA_BASE
    / "Extrator de Currículo - LATTES"
    / "Currículos dos Egressos - LATTES"
)

# fontes de publicações
ARQUIVO_OPENALEX = (
    PASTA_BASE
    / "Enriquecimento de dados - OPENALEX"
    / "Estratégia 1"
    / "publicacoes_egressos_openalex.xlsx"
)

ARQUIVO_CROSSREF = (
    PASTA_BASE
    / "Enriquecimento de dados - CROSSREF"
    / "Estratégia 1"
    / "publicacoes_crossref_lattes.xlsx"
)

# pasta de saída deste módulo
PASTA_SAIDA = PASTA_BASE / "Modulo II" / "Similaridade Semântica"
PASTA_SAIDA.mkdir(parents=True, exist_ok=True)

print("Entidades:", ARQUIVO_ENTIDADES)
print("Base integrada:", ARQUIVO_BASE_INTEGRADA)
print("Lattes:", PASTA_LATTES)
print("OpenAlex:", ARQUIVO_OPENALEX)
print("Crossref:", ARQUIVO_CROSSREF)
print("Saída:", PASTA_SAIDA)

"""## 4. Validação dos arquivos

Antes de iniciar o processamento, verificamos se as fontes esperadas existem.

Essa etapa evita que o notebook prossiga utilizando uma fonte ausente ou um caminho diferente do definido no projeto.
"""

arquivos_entrada = {
    "01_entidades.xlsx": ARQUIVO_ENTIDADES,
    "03_base_integrada.xlsx": ARQUIVO_BASE_INTEGRADA,
    "OpenAlex": ARQUIVO_OPENALEX,
    "Crossref": ARQUIVO_CROSSREF,
}

for nome, caminho in arquivos_entrada.items():
    print(f"{nome:30} | {'OK' if caminho.exists() else 'NÃO ENCONTRADO'}")

arquivos_lattes = sorted(PASTA_LATTES.glob("*.xml"))
print(f"Currículos Lattes encontrados: {len(arquivos_lattes)}")

"""## 5. Leitura das bases

Nesta etapa carregamos as bases produzidas anteriormente.

A leitura não altera os dados originais.
"""

entidades = pd.read_excel(ARQUIVO_ENTIDADES)
base_integrada = pd.read_excel(ARQUIVO_BASE_INTEGRADA)
openalex = pd.read_excel(ARQUIVO_OPENALEX)
crossref = pd.read_excel(ARQUIVO_CROSSREF)

print("Entidades:", entidades.shape)
print("Base integrada:", base_integrada.shape)
print("OpenAlex:", openalex.shape)
print("Crossref:", crossref.shape)

"""## 6. Inspeção das informações de identificação

O `ID_ENTIDADE` é a chave principal desta etapa.

Os identificadores Lattes e ORCID continuam sendo mantidos para rastreabilidade, mas não será executado novamente o processo de desambiguação.
"""

print("Colunas de entidades:")
print(entidades.columns.tolist())

print("\nColunas da base integrada:")
print(base_integrada.columns.tolist())

print("\nExemplo de entidades:")
display(entidades.head())

"""## 7. Normalização dos identificadores de apoio

A normalização abaixo serve somente para relacionar os XMLs Lattes às entidades já existentes.

Ela não cria novas entidades.
"""

def limpar(valor):
    if pd.isna(valor):
        return ""
    return str(valor).strip()

def normalizar_lattes(valor):
    return re.sub(r"\D", "", limpar(valor))

def normalizar_orcid(valor):
    valor = limpar(valor).upper()
    valor = valor.replace("HTTPS://ORCID.ORG/", "")
    valor = valor.replace("HTTP://ORCID.ORG/", "")
    return valor

entidades["ID_LATTES_NORMALIZADO"] = entidades["ID_LATTES"].apply(normalizar_lattes)
entidades["ORCID_NORMALIZADO"] = entidades["ORCID"].apply(normalizar_orcid)

mapa_lattes = (
    entidades[
        entidades["ID_LATTES_NORMALIZADO"] != ""
    ]
    .drop_duplicates("ID_LATTES_NORMALIZADO")
    .set_index("ID_LATTES_NORMALIZADO")["ID_ENTIDADE"]
    .to_dict()
)

print("Identificadores Lattes mapeados:", len(mapa_lattes))

"""## 8. Estrutura dos currículos Lattes

Os currículos Lattes serão utilizados para complementar a informação semântica.

Serão extraídos, quando disponíveis:

- identificação;
- resumo do currículo;
- resumo profissional;
- formação;
- produção;
- atuação profissional.

A associação com a entidade ocorrerá pelo `ID_LATTES`.
"""

def texto_xml(elemento):
    if elemento is None:
        return ""
    texto = " ".join(
        t.strip()
        for t in elemento.itertext()
        if t and t.strip()
    )
    return re.sub(r"\s+", " ", texto).strip()

def primeiro(root, caminhos):
    for caminho in caminhos:
        resultado = root.xpath(caminho)
        if resultado:
            return resultado[0]
    return None

def coletar_texto_por_fragmentos(root, fragmentos, minimo=20):
    expressao = ".//*[" + " or ".join(
        f"contains(local-name(), '{fragmento}')"
        for fragmento in fragmentos
    ) + "]"

    valores = []

    for elemento in root.xpath(expressao):
        texto = texto_xml(elemento)

        if len(texto) >= minimo:
            valores.append(texto)

    return " ".join(dict.fromkeys(valores))

"""## 9. Extração dos dados Lattes

A função abaixo transforma cada XML em um registro estruturado.

O objetivo é preservar o conteúdo textual necessário para a análise semântica.
"""

def extrair_lattes(caminho):
    arvore = etree.parse(
        str(caminho),
        etree.XMLParser(
            recover=True,
            huge_tree=True
        )
    )

    root = arvore.getroot()

    nome = texto_xml(
        primeiro(root, [".//IDENTIFICACAO/NOME"])
    )

    id_lattes = texto_xml(
        primeiro(
            root,
            [
                ".//IDENTIFICACAO/@ID-LATTES",
                ".//IDENTIFICACAO/ID-LATTES"
            ]
        )
    )

    resumo_cv = texto_xml(
        primeiro(root, [".//RESUMO-CV/TEXTO"])
    )

    resumo_profissional = texto_xml(
        primeiro(root, [".//RESUMO-PROFISSIONAL/TEXTO"])
    )

    formacao = coletar_texto_por_fragmentos(
        root,
        ["FORMACAO", "FORMAÇÃO"]
    )

    producao = coletar_texto_por_fragmentos(
        root,
        ["PRODUCAO", "PRODUÇÃO"],
        minimo=30
    )

    atuacao = coletar_texto_por_fragmentos(
        root,
        ["ATUACAO", "ATUAÇÃO"],
        minimo=30
    )

    return {
        "NOME_LATTES": nome,
        "ID_LATTES": id_lattes,
        "RESUMO_CV": resumo_cv,
        "RESUMO_PROFISSIONAL": resumo_profissional,
        "FORMACAO_LATTES": formacao,
        "PRODUCAO_LATTES": producao,
        "ATUACAO_LATTES": atuacao,
        "ARQUIVO_LATTES": caminho.name
    }

"""## 10. Construção da base Lattes

Cada currículo é associado ao `ID_ENTIDADE` já existente.

Currículos sem correspondência de identificador são mantidos para auditoria, mas não entram automaticamente na integração semântica.
"""

registros_lattes = []

for caminho in tqdm(arquivos_lattes):
    try:
        registro = extrair_lattes(caminho)

        registro["ID_LATTES_NORMALIZADO"] = normalizar_lattes(
            registro["ID_LATTES"]
        )

        registro["ID_ENTIDADE"] = mapa_lattes.get(
            registro["ID_LATTES_NORMALIZADO"],
            ""
        )

        registros_lattes.append(registro)

    except Exception as erro:
        print(
            "Erro ao processar:",
            caminho.name,
            "|",
            erro
        )

lattes = pd.DataFrame(registros_lattes)

print("Currículos processados:", len(lattes))
print(
    "Currículos associados a entidade:",
    (lattes["ID_ENTIDADE"] != "").sum()
)

display(lattes.head())

"""## 11. Preparação das publicações OpenAlex

O OpenAlex contribui principalmente com informação temática.

Serão utilizados, quando disponíveis:

- título;
- tópico principal;
- subcampo;
- campo;
- grande área;
- conceitos/palavras-chave;
- ODS associados.

Essas informações serão agregadas por `ID_ENTIDADE`.
"""

def valor_campo(row, nomes):
    for nome in nomes:
        if nome in row.index and pd.notna(row[nome]):
            valor = str(row[nome]).strip()
            if valor:
                return valor
    return ""

campos_openalex = [
    "Titulo_Trabalho",
    "Topico_Principal",
    "Subcampo_Conhecimento",
    "Campo_Conhecimento",
    "Grande_Area_Conhecimento",
    "Palavras_Chave_Conceitos",
    "ODS_ONU_Associados"
]

registros_openalex = []

for _, row in openalex.iterrows():
    id_lattes = normalizar_lattes(
        valor_campo(row, ["ID_Lattes"])
    )

    id_entidade = mapa_lattes.get(id_lattes, "")

    if not id_entidade:
        continue

    partes = [
        valor_campo(row, [campo])
        for campo in campos_openalex
    ]

    partes = [parte for parte in partes if parte]

    if partes:
        registros_openalex.append({
            "ID_ENTIDADE": id_entidade,
            "TEXTO_OPENALEX": " | ".join(partes)
        })

openalex_semantico = pd.DataFrame(
    registros_openalex,
    columns=["ID_ENTIDADE", "TEXTO_OPENALEX"]
)

if not openalex_semantico.empty:
    openalex_semantico = (
        openalex_semantico
        .groupby("ID_ENTIDADE", as_index=False)
        ["TEXTO_OPENALEX"]
        .agg(" ".join)
    )

print("Entidades com informação OpenAlex:", len(openalex_semantico))

"""## 12. Preparação das publicações Crossref

O Crossref complementa a descrição da produção científica.

Quando disponíveis, serão considerados:

- título;
- autores;
- ano;
- periódico;
- editora.

Os registros também serão agregados por `ID_ENTIDADE`.
"""

campos_crossref = [
    "Titulo_Trabalho",
    "Título",
    "Autores",
    "Ano_Publicacao",
    "Ano",
    "Revista_Periodico",
    "Journal",
    "Publisher"
]

registros_crossref = []

for _, row in crossref.iterrows():
    id_lattes = normalizar_lattes(
        valor_campo(row, ["ID_Lattes"])
    )

    id_entidade = mapa_lattes.get(id_lattes, "")

    if not id_entidade:
        continue

    partes = [
        valor_campo(row, [campo])
        for campo in campos_crossref
    ]

    partes = [parte for parte in partes if parte]

    if partes:
        registros_crossref.append({
            "ID_ENTIDADE": id_entidade,
            "TEXTO_CROSSREF": " | ".join(partes)
        })

crossref_semantico = pd.DataFrame(
    registros_crossref,
    columns=["ID_ENTIDADE", "TEXTO_CROSSREF"]
)

if not crossref_semantico.empty:
    crossref_semantico = (
        crossref_semantico
        .groupby("ID_ENTIDADE", as_index=False)
        ["TEXTO_CROSSREF"]
        .agg(" ".join)
    )

print("Entidades com informação Crossref:", len(crossref_semantico))

"""## 13. Integração das fontes

Nesta etapa reunimos as informações mantendo `ID_ENTIDADE` como chave.

A identidade não é reconstruída.

O que será criado agora são os campos necessários para a análise semântica.
"""

base = entidades[
    [
        "ID_ENTIDADE",
        "NOME_CANONICO",
        "NOME_NORMALIZADO",
        "ID_LATTES",
        "ORCID"
    ]
].copy()

base = base.merge(
    lattes.drop(
        columns=["ID_LATTES_NORMALIZADO", "ID_LATTES"],
        errors="ignore"
    ),
    on="ID_ENTIDADE",
    how="left"
)

base = base.merge(
    openalex_semantico,
    on="ID_ENTIDADE",
    how="left"
)

base = base.merge(
    crossref_semantico,
    on="ID_ENTIDADE",
    how="left"
)

base = base.fillna("")

print("Entidades na base semântica:", len(base))
display(base.head())

"""## 14. Construção do Documento de Formação

O Documento de Formação representa o conjunto de informações acadêmicas e científicas disponíveis para cada egresso.

São combinados:

- resumo do currículo;
- formação;
- produção;
- temas e áreas das publicações OpenAlex;
- informações bibliográficas do Crossref.
"""

def juntar_textos(*valores):
    textos = []

    for valor in valores:
        if pd.isna(valor):
            continue

        valor = str(valor).strip()

        if valor:
            textos.append(valor)

    return " ".join(dict.fromkeys(textos))

base["DOCUMENTO_FORMACAO"] = base.apply(
    lambda row: juntar_textos(
        row["RESUMO_CV"],
        row["FORMACAO_LATTES"],
        row["PRODUCAO_LATTES"],
        row["TEXTO_OPENALEX"],
        row["TEXTO_CROSSREF"]
    ),
    axis=1
)

"""## 15. Construção do Documento de Atuação Profissional

O Documento de Atuação representa as informações profissionais disponíveis no currículo Lattes.

São utilizados:

- resumo profissional;
- atuação profissional;
- resumo curricular como contexto complementar.
"""

base["DOCUMENTO_ATUACAO"] = base.apply(
    lambda row: juntar_textos(
        row["RESUMO_PROFISSIONAL"],
        row["ATUACAO_LATTES"],
        row["RESUMO_CV"]
    ),
    axis=1
)

base["TAMANHO_FORMACAO"] = base["DOCUMENTO_FORMACAO"].str.len()
base["TAMANHO_ATUACAO"] = base["DOCUMENTO_ATUACAO"].str.len()

base["TEM_FORMACAO"] = base["TAMANHO_FORMACAO"] >= 50
base["TEM_ATUACAO"] = base["TAMANHO_ATUACAO"] >= 50

print("Formação suficiente:", int(base["TEM_FORMACAO"].sum()))
print("Atuação suficiente:", int(base["TEM_ATUACAO"].sum()))
print(
    "Formação e atuação disponíveis:",
    int((base["TEM_FORMACAO"] & base["TEM_ATUACAO"]).sum())
)

"""## 16. Inspeção dos documentos semânticos

Antes de gerar embeddings, é importante verificar se os textos construídos fazem sentido.

Essa inspeção permite identificar documentos vazios, muito curtos ou contaminados por informações inadequadas.
"""

display(
    base[
        [
            "ID_ENTIDADE",
            "NOME_CANONICO",
            "DOCUMENTO_FORMACAO",
            "DOCUMENTO_ATUACAO"
        ]
    ].head(5)
)

"""## 17. Preparação do modelo

Será utilizado inicialmente o modelo:

`sentence-transformers/paraphrase-multilingual-mpnet-base-v2`

Ele será utilizado como **baseline** para a análise semântica.

A escolha do modelo não encerra a etapa metodológica: posteriormente outros modelos poderão ser comparados.
"""

MODELO = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"

modelo = SentenceTransformer(MODELO)

print("Modelo carregado:", MODELO)

"""## 18. Seleção dos egressos com dados suficientes

A comparação só será realizada quando houver conteúdo suficiente nos dois documentos.

Os demais registros permanecerão na base final, mas sem score.
"""

validos = (
    base["TEM_FORMACAO"]
    & base["TEM_ATUACAO"]
)

indices_validos = base.index[validos].tolist()

print("Registros aptos para comparação:", len(indices_validos))
print("Registros sem comparação:", len(base) - len(indices_validos))

"""## 19. Geração dos embeddings

Cada Documento de Formação e cada Documento de Atuação será transformado em um vetor numérico.

Esses vetores representam semanticamente os textos no espaço do modelo.
"""

textos_formacao = base.loc[
    indices_validos,
    "DOCUMENTO_FORMACAO"
].tolist()

textos_atuacao = base.loc[
    indices_validos,
    "DOCUMENTO_ATUACAO"
].tolist()

embeddings_formacao = modelo.encode(
    textos_formacao,
    batch_size=16,
    show_progress_bar=True,
    normalize_embeddings=True
)

embeddings_atuacao = modelo.encode(
    textos_atuacao,
    batch_size=16,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Dimensão dos embeddings:", embeddings_formacao.shape)

"""## 20. Cálculo da similaridade semântica

A comparação será feita por **similaridade do cosseno**.

Como os embeddings foram normalizados, o produto escalar entre os vetores também representa a similaridade do cosseno.
"""

similaridades = np.diag(
    cosine_similarity(
        embeddings_formacao,
        embeddings_atuacao
    )
)

scores = np.full(len(base), np.nan)

for posicao, indice in enumerate(indices_validos):
    posicao_base = base.index.get_loc(indice)
    scores[posicao_base] = similaridades[posicao]

base["SIMILARIDADE_COSSENO"] = scores

base["INDICE_SIMILARIDADE_0_100"] = (
    base["SIMILARIDADE_COSSENO"] * 100
).clip(0, 100)

display(
    base[
        [
            "ID_ENTIDADE",
            "NOME_CANONICO",
            "SIMILARIDADE_COSSENO",
            "INDICE_SIMILARIDADE_0_100"
        ]
    ].dropna().head(10)
)

"""## 21. Classificação preliminar

Para facilitar a inspeção inicial, será criada uma classificação preliminar:

- `alta similaridade`: índice >= 70;
- `similaridade intermediária`: índice >= 45 e < 70;
- `baixa similaridade`: índice < 45;
- `sem dados`: não foi possível calcular.

Esses limites são **operacionais e preliminares**. A validação humana é necessária antes de qualquer interpretação substantiva.

O índice não representa percentual de empregabilidade.
"""

def classificar_similaridade(valor):
    if pd.isna(valor):
        return "sem dados"

    if valor >= 70:
        return "alta similaridade"

    if valor >= 45:
        return "similaridade intermediária"

    return "baixa similaridade"

base["CATEGORIA_PRELIMINAR"] = (
    base["INDICE_SIMILARIDADE_0_100"]
    .apply(classificar_similaridade)
)

display(
    base["CATEGORIA_PRELIMINAR"]
    .value_counts(dropna=False)
)

"""## 22. Base de validação humana

A validação humana será utilizada para verificar se a proximidade calculada pelo modelo corresponde à relação observável entre formação e atuação.

A base mantém os textos originais utilizados no cálculo.
"""

validacao = base[
    [
        "ID_ENTIDADE",
        "NOME_CANONICO",
        "ID_LATTES",
        "ORCID",
        "DOCUMENTO_FORMACAO",
        "DOCUMENTO_ATUACAO",
        "SIMILARIDADE_COSSENO",
        "INDICE_SIMILARIDADE_0_100",
        "CATEGORIA_PRELIMINAR"
    ]
].copy()

validacao["AVALIACAO_HUMANA"] = ""
validacao["JUSTIFICATIVA_AVALIACAO"] = ""
validacao["OBSERVACAO"] = ""

display(validacao.head())

"""## 23. Indicadores de qualidade

Os indicadores abaixo permitem acompanhar a cobertura da análise antes da exportação.
"""

resumo = pd.DataFrame({
    "INDICADOR": [
        "Entidades",
        "Formação suficiente",
        "Atuação suficiente",
        "Formação e atuação disponíveis",
        "Scores calculados",
        "Entidades duplicadas"
    ],
    "VALOR": [
        len(base),
        int(base["TEM_FORMACAO"].sum()),
        int(base["TEM_ATUACAO"].sum()),
        int(validos.sum()),
        int(base["SIMILARIDADE_COSSENO"].notna().sum()),
        int(base["ID_ENTIDADE"].duplicated().sum())
    ]
})

display(resumo)

"""## 24. Definição dos arquivos de saída

Os resultados serão armazenados na pasta:

`RAGI 2026 2/Modulo II/Similaridade Semântica`

Arquivos:

- `03_similaridade_formacao_atuacao.xlsx`;
- `04_validacao_humana_similaridade.xlsx`;
- `05_resumo_similaridade.xlsx`;
- `embeddings_formacao.npy`;
- `embeddings_atuacao.npy`;
- `metadados_embeddings.xlsx`.
"""

ARQUIVO_RESULTADO = PASTA_SAIDA / "03_similaridade_formacao_atuacao.xlsx"
ARQUIVO_VALIDACAO = PASTA_SAIDA / "04_validacao_humana_similaridade.xlsx"
ARQUIVO_RESUMO = PASTA_SAIDA / "05_resumo_similaridade.xlsx"
ARQUIVO_EMB_FORMACAO = PASTA_SAIDA / "embeddings_formacao.npy"
ARQUIVO_EMB_ATUACAO = PASTA_SAIDA / "embeddings_atuacao.npy"
ARQUIVO_META = PASTA_SAIDA / "metadados_embeddings.xlsx"

"""## 25. Exportação dos resultados

A exportação mantém a rastreabilidade por `ID_ENTIDADE`.

Os embeddings também são salvos separadamente para que possam ser reutilizados em etapas posteriores de PLN sem necessidade de recalcular os vetores.
"""

base.to_excel(ARQUIVO_RESULTADO, index=False)
validacao.to_excel(ARQUIVO_VALIDACAO, index=False)
resumo.to_excel(ARQUIVO_RESUMO, index=False)

np.save(ARQUIVO_EMB_FORMACAO, embeddings_formacao)
np.save(ARQUIVO_EMB_ATUACAO, embeddings_atuacao)

metadados_embeddings = base.loc[
    indices_validos,
    [
        "ID_ENTIDADE",
        "NOME_CANONICO",
        "ID_LATTES",
        "ORCID"
    ]
].copy()

metadados_embeddings["POSICAO_EMBEDDING"] = range(
    len(metadados_embeddings)
)

metadados_embeddings.to_excel(
    ARQUIVO_META,
    index=False
)

print("Exportação concluída.")

"""## 26. Validação final dos arquivos

A última etapa verifica se todos os arquivos previstos foram realmente criados.
"""

arquivos_saida = [
    ARQUIVO_RESULTADO,
    ARQUIVO_VALIDACAO,
    ARQUIVO_RESUMO,
    ARQUIVO_EMB_FORMACAO,
    ARQUIVO_EMB_ATUACAO,
    ARQUIVO_META
]

for caminho in arquivos_saida:
    print(
        f"{caminho.name:45} | "
        f"{'OK' if caminho.exists() else 'ERRO'}"
    )

"""## 27. Limitações metodológicas

A similaridade semântica representa proximidade entre os textos utilizados.

Ela não deve ser interpretada isoladamente como:

- empregabilidade;
- sucesso profissional;
- qualidade da formação;
- impacto profissional;
- causalidade entre formação e trajetória profissional.

O resultado depende da cobertura das fontes, da qualidade dos textos, do modelo utilizado e da validação humana.

## 28. Conexão com o restante do projeto

```text
Lattes + OpenAlex + Crossref
            ↓
Normalização e Desambiguação
            ↓
        ID_ENTIDADE
            ↓
      Base Integrada
            ↓
 ┌───────────────────────┐
 │ Documento de Formação │
 │ Documento de Atuação  │
 └───────────────────────┘
            ↓
       Embeddings
            ↓
 Similaridade Semântica
            ↓
    Validação Humana
            ↓
    Indicadores RAGI
```

Este módulo acrescenta a camada de PLN sobre a estrutura de entidades construída anteriormente.
"""