# -*- coding: utf-8 -*-
"""ClassTemAuto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C11nwqYPFFBhicfNj18-9vkPHI6qrH8T

# Classificação Temática Automática — Módulo II (RAGI)

## O que este notebook faz

Este notebook implementa a seção **Classificação Temática Automática** do Módulo II do projeto RAGI. Sua finalidade é transformar um conjunto inicialmente cru de produções científicas dos egressos do PPGCOM (muitas vezes contendo apenas o título) em informação estruturada sobre:

1. **Área do conhecimento** predominante de cada produção;
2. **Aderência aos 17 Objetivos de Desenvolvimento Sustentável (ODS) da ONU**;
3. **Consolidação por egresso** (`ID_ENTIDADE`), permitindo leituras agregadas para o dashboard.

Em outras palavras: a partir de títulos e (quando existirem) resumos e metadados, o notebook produz uma **classificação temática auditável**, com indicadores de confiança e trilha de origem (OpenAlex, Crossref ou Zero-Shot).

Este notebook responde diretamente a duas atividades previstas no projeto:

| Seção do projeto | Atividade correspondente |
|---|---|
| Mapear taxonomia de aderência aos ODS da ONU | Definir categorias, critérios e relação entre temas da produção científica e os ODS |
| Validar e calibrar os modelos com amostra real de egressos | Testar os modelos de classificação/agrupamento e ajustar seus parâmetros com dados reais |

# Célula 1 — Instalação e configuração inicial
"""

# ============================================================
# CÉLULA 1 — Instalação de dependências e configuração global
# ============================================================

!pip install -q transformers sentence-transformers torch openpyxl requests rapidfuzz tqdm pyarrow

from google.colab import drive
drive.mount('/content/drive')

import os, re, json, time, unicodedata, warnings
import requests, numpy as np, pandas as pd

from pathlib import Path
from urllib.parse import quote
from rapidfuzz import fuzz
from tqdm.auto import tqdm

warnings.filterwarnings('ignore')

# ------------------------------------------------------------
# PARÂMETROS PRINCIPAIS
# ------------------------------------------------------------
EMAIL_POLITE = 'fernando23@discente.ufg.br'

BASE = Path('/content/drive/MyDrive/Gestao_Informacao/8 periodo/Residência/RAGI 2026 2')
PASTA_SAIDA = BASE / 'Modulo II' / 'Classificação Temática Automática'
PASTA_SAIDA.mkdir(parents=True, exist_ok=True)

USAR_CAPTURA_POR_ORCID         = False
USAR_ENRIQUECIMENTO_POR_TITULO = True
MAX_ENRIQUECIMENTO_POR_TITULO  = None
MAX_ENTIDADES                  = None
MAX_WORKS_POR_ENTIDADE         = 100

# Limiares da classificação
LIMIAR_AREAS_ADERENTES = 0.30   # áreas secundárias
LIMIAR_ODS_ADERENTES   = 0.45   # ODS aderentes (subimos de 0.30 → 0.45)

ARQUIVO_CACHE = PASTA_SAIDA / 'cache_enriquecimento.json'

# ------------------------------------------------------------
# CHECK DE GPU (evita surpresa de 4h de CPU)
# ------------------------------------------------------------
import torch
GPU_OK = torch.cuda.is_available()
print('✔ Configuração concluída')
print('  Pasta de saída :', PASTA_SAIDA)
print('  E-mail (API)   :', EMAIL_POLITE or '(vazio — preencher!)')
if GPU_OK:
    print('  GPU            : ✔', torch.cuda.get_device_name(0))
else:
    print('  GPU            : ✖ NÃO DISPONÍVEL')
    print('    → Ambiente de execução → Alterar tipo → T4 GPU → Reiniciar sessão')

"""# Célula 2 — Localização automática dos arquivos de entrada

"""

# ============================================================
# CÉLULA 2 — Localizar arquivos de entrada
# ============================================================
# O notebook procura automaticamente:
#   - base integrada de entidades (03_base_integrada.xlsx)
#   - planilha de entidades (01_entidades.xlsx)
#   - planilha de egressos com títulos
# ============================================================

def localizar_arquivo(padroes, raiz=BASE):
    """Procura o primeiro arquivo que casa com algum dos padrões."""
    for padrao in padroes:
        for caminho in raiz.rglob(padrao):
            if caminho.is_file() and not caminho.name.startswith('~$'):
                return caminho
    return None

def candidatos_fora_da_saida(padrao):
    """Lista arquivos do padrão, exceto os da pasta de saída."""
    return [
        p for p in BASE.rglob(padrao)
        if p.is_file()
        and not p.name.startswith('~$')
        and PASTA_SAIDA not in p.parents
    ]

ARQUIVO_BASE_INTEGRADA = localizar_arquivo(['*03_base_integrada*.xlsx'])
ARQUIVO_ENTIDADES      = localizar_arquivo(['*01_entidades*.xlsx'])

# Se você souber o caminho exato da planilha de títulos, informe aqui:
ARQUIVO_EGRESSOS_TITULOS = None

CANDIDATOS_TITULOS = []
if ARQUIVO_EGRESSOS_TITULOS:
    CANDIDATOS_TITULOS.append(Path(ARQUIVO_EGRESSOS_TITULOS))

CANDIDATOS_TITULOS += candidatos_fora_da_saida('*egressos*.xlsx')
CANDIDATOS_TITULOS += candidatos_fora_da_saida('*openalex*.xlsx')
CANDIDATOS_TITULOS += candidatos_fora_da_saida('*crossref*.xlsx')
CANDIDATOS_TITULOS += candidatos_fora_da_saida('*titulos*.xlsx')
CANDIDATOS_TITULOS += candidatos_fora_da_saida('*publicacoes_titulos*.xlsx')

# Remove duplicados, preservando a ordem de prioridade
CANDIDATOS_TITULOS = list(dict.fromkeys(CANDIDATOS_TITULOS))

print('✔ Base integrada :', ARQUIVO_BASE_INTEGRADA)
print('✔ Entidades      :', ARQUIVO_ENTIDADES)
print('\nCandidatos a planilha de títulos-alvo:')
for c in CANDIDATOS_TITULOS:
    print('  -', c.name)

"""# Célula 3 — Funções de normalização

"""

# ============================================================
# CÉLULA 3 — Normalização de identificadores e texto
# Inclui limpeza de ruído dos títulos (item 1 da melhoria)
# ============================================================

def limpar_valor(valor):
    if pd.isna(valor):
        return ''
    return str(valor).strip()

def remover_acentos(texto):
    texto = unicodedata.normalize('NFKD', texto)
    return ''.join(c for c in texto if not unicodedata.combining(c))

def normalizar_texto(valor):
    valor = limpar_valor(valor)
    if not valor:
        return ''
    valor = remover_acentos(valor).lower()
    valor = re.sub(r'[^a-z0-9\s]', ' ', valor)
    return re.sub(r'\s+', ' ', valor).strip()

def normalizar_lattes(valor):
    return re.sub(r'\D', '', limpar_valor(valor))

def normalizar_orcid(valor):
    valor = limpar_valor(valor)
    if not valor:
        return ''
    valor = re.sub(r'^https?://orcid\.org/', '', valor, flags=re.IGNORECASE)
    valor = re.sub(r'^orcid:\s*', '', valor, flags=re.IGNORECASE)
    valor = re.sub(r'\s+', '', valor)
    if len(valor) == 16 and valor.count('-') == 0:
        valor = '-'.join([valor[i:i+4] for i in range(0, 16, 4)])
    return valor.strip()

def normalizar_doi(valor):
    valor = limpar_valor(valor).lower()
    for prefixo in ['https://doi.org/', 'http://doi.org/', 'doi:']:
        valor = valor.replace(prefixo, '')
    return valor.strip().rstrip('/')

# NOVO: limpeza de ruído dos títulos do scraper
def limpar_titulo_ruido(titulo):
    """Remove ( arquivo ), (arquivo indisponível), entidades HTML etc."""
    t = str(titulo) if not pd.isna(titulo) else ''
    t = re.sub(r'\(\s*arquivo(\s+indispon[íi]vel)?\s*\)', '', t, flags=re.IGNORECASE)
    t = re.sub(r'\(\s*ARQUIVO\s*\)', '', t)
    t = t.replace('&amp;', '&').replace('&#x0D;', ' ')
    t = t.replace('&nbsp;', ' ').replace('&lt;', '<').replace('&gt;', '>')
    t = re.sub(r'\s+', ' ', t).strip(' .;,-')
    return t

def localizar_coluna(df, alternativas):
    mapa = {normalizar_texto(c): c for c in df.columns}
    for alternativa in alternativas:
        chave = normalizar_texto(alternativa)
        if chave in mapa:
            return mapa[chave]
    return None

def combinar_campos_texto(df, colunas):
    if not colunas:
        return pd.Series([''] * len(df))
    def juntar(linha):
        valores = [str(v).strip() for v in linha if str(v).strip()]
        return '; '.join(dict.fromkeys(valores))
    return df[colunas].fillna('').apply(juntar, axis=1)

print('✔ Funções de normalização carregadas (com limpeza de título)')

"""# Célula 4 — Taxonomia dos ODS e áreas do conhecimento

"""

# ============================================================
# CÉLULA 4 — Taxonomia de ODS e áreas do conhecimento
# ============================================================
# Esta célula materializa a ATIVIDADE 1 do projeto:
# "Mapear taxonomia de aderência aos ODS da ONU".
# ============================================================

ODS_MAPA = {
    1:  'Erradicação da pobreza',
    2:  'Fome zero e agricultura sustentável',
    3:  'Saúde e bem-estar',
    4:  'Educação de qualidade',
    5:  'Igualdade de gênero',
    6:  'Água potável e saneamento',
    7:  'Energia limpa e acessível',
    8:  'Trabalho decente e crescimento econômico',
    9:  'Indústria, inovação e infraestrutura',
    10: 'Redução das desigualdades',
    11: 'Cidades e comunidades sustentáveis',
    12: 'Consumo e produção responsáveis',
    13: 'Ação contra a mudança global do clima',
    14: 'Vida na água',
    15: 'Vida terrestre',
    16: 'Paz, justiça e instituições eficazes',
    17: 'Parcerias e meios de implementação'
}

ODS_LABELS = list(ODS_MAPA.values())
ODS_NOME_PARA_CODIGO = {nome: codigo for codigo, nome in ODS_MAPA.items()}

AREAS_LABELS = [
    'Ciências Exatas e da Terra',
    'Ciências Biológicas',
    'Engenharias e Computação',
    'Ciências da Saúde',
    'Ciências Agrárias',
    'Ciências Sociais Aplicadas, Administração e Gestão da Informação',
    'Ciências Humanas e Educação',
    'Linguística, Letras e Artes',
    'Interdisciplinar'
]

def formatar_rotulo_ods(rotulo):
    """Adiciona o código numérico ao rótulo, ex.: '3 Saúde e bem-estar'."""
    codigo = ODS_NOME_PARA_CODIGO.get(rotulo)
    return f'{codigo} {rotulo}' if codigo else rotulo

print(f'✔ {len(ODS_LABELS)} ODS cadastrados')
print(f'✔ {len(AREAS_LABELS)} áreas do conhecimento cadastradas')

"""# Célula 5 — Funções de consulta às APIs (OpenAlex + Crossref)

"""

# ============================================================
# CÉLULA 5 — Funções de consulta às APIs OpenAlex e Crossref
# ============================================================
# Faz requisições com retry, limpa dados e devolve linhas
# padronizadas (título, DOI, ano, resumo, temas, ODS...).
# ============================================================

def api_get_json(url, params=None, headers=None, timeout=20, tentativas=3):
    """GET com retry exponencial simples."""
    for tentativa in range(tentativas):
        try:
            resposta = requests.get(url, params=params, headers=headers, timeout=timeout)
            if resposta.status_code == 200:
                return resposta.json()
            if resposta.status_code in (429, 500, 502, 503, 504):
                time.sleep(2 * (tentativa + 1))
                continue
            return None
        except Exception:
            time.sleep(2 * (tentativa + 1))
    return None

def limpar_jats(texto):
    """Remove tags XML/JATS de resumos do Crossref."""
    if not texto:
        return ''
    texto = re.sub(r'<[^>]+>', ' ', str(texto))
    return re.sub(r'\s+', ' ', texto).strip()

def reconstruir_abstract_openalex(inverted_index):
    """Reconstrói resumo do OpenAlex a partir do índice invertido."""
    if not inverted_index:
        return ''
    pares = []
    for palavra, posicoes in inverted_index.items():
        for pos in posicoes:
            pares.append((pos, palavra))
    pares.sort(key=lambda x: x[0])
    return ' '.join(palavra for _, palavra in pares)

def parse_openalex_work(work):
    """Converte um trabalho do OpenAlex em linha padronizada."""
    titulo = (work.get('title') or '').strip()
    doi = (work.get('doi') or '').strip().replace('https://doi.org/', '').replace('http://doi.org/', '')
    ano = work.get('publication_year', '')

    resumo = reconstruir_abstract_openalex(work.get('abstract_inverted_index'))

    # Coleta temas a partir de topics, concepts e keywords
    temas = []
    for topic in (work.get('topics') or [])[:8]:
        if isinstance(topic, dict):
            temas.append(topic.get('display_name', ''))
            temas.append((topic.get('subfield') or {}).get('display_name', ''))
            temas.append((topic.get('field') or {}).get('display_name', ''))
            temas.append((topic.get('domain') or {}).get('display_name', ''))
    for concept in (work.get('concepts') or [])[:12]:
        if isinstance(concept, dict):
            temas.append(concept.get('display_name', ''))
    for kw in (work.get('keywords') or [])[:8]:
        temas.append(kw.get('display_name', '') if isinstance(kw, dict) else str(kw))
    temas = list(dict.fromkeys([t for t in temas if t]))[:50]

    # Periódico
    periodico = ''
    source = ((work.get('primary_location') or {}).get('source') or {})
    if isinstance(source, dict):
        periodico = source.get('display_name', '')

    # ODS vindos do OpenAlex
    ods = []
    for goal in (work.get('sustainable_development_goals') or []):
        if not isinstance(goal, dict):
            continue
        url_goal = goal.get('id', '') or ''
        nome_goal = goal.get('display_name', '') or ''
        codigo = None
        m = re.search(r'/(\d+)$', url_goal)
        if m:
            codigo = m.group(1)
        if codigo and codigo.isdigit():
            nome_pt = ODS_MAPA.get(int(codigo), nome_goal)
            ods.append(f'{codigo} {nome_pt}'.strip())
        elif nome_goal:
            ods.append(nome_goal)
    ods = list(dict.fromkeys([o for o in ods if o]))

    return {
        'TITULO': titulo,
        'DOI': doi,
        'ANO': str(ano) if ano else '',
        'RESUMO': resumo,
        'TEMAS': '; '.join(temas),
        'PERIODICO': periodico,
        'ODS_OPENALEX': '; '.join(ods),
        'FONTE': 'OpenAlex API'
    }

def parse_crossref_item(item):
    """Converte um trabalho do Crossref em linha padronizada."""
    titulo = item.get('title', '')
    if isinstance(titulo, list):
        titulo = titulo[0] if titulo else ''
    titulo = str(titulo).strip()

    doi = item.get('DOI', '') or ''
    resumo = limpar_jats(item.get('abstract', ''))

    assuntos = item.get('subject', []) or []
    if isinstance(assuntos, str):
        assuntos = [assuntos]
    assuntos = [str(a).strip() for a in assuntos if str(a).strip()]

    periodico = item.get('container-title', '')
    if isinstance(periodico, list):
        periodico = periodico[0] if periodico else ''
    periodico = str(periodico).strip()

    issued = item.get('issued', {}) or {}
    date_parts = issued.get('date-parts', [[None]])
    ano = ''
    if date_parts and date_parts[0]:
        ano = date_parts[0][0] or ''

    return {
        'TITULO': titulo,
        'DOI': doi,
        'ANO': str(ano) if ano else '',
        'RESUMO': resumo,
        'TEMAS': '; '.join(dict.fromkeys(assuntos)),
        'PERIODICO': periodico,
        'ODS_OPENALEX': '',
        'FONTE': 'Crossref API'
    }

def melhor_candidato(candidatos, titulo, limiar=92):
    """Escolhe o melhor resultado de busca por título (similaridade alta)."""
    if not candidatos or not titulo:
        return None
    titulo_norm = normalizar_texto(titulo)
    melhor, melhor_score = None, 0
    for candidato in candidatos:
        candidato_norm = normalizar_texto(candidato.get('TITULO', ''))
        if not candidato_norm:
            continue
        score = fuzz.token_set_ratio(titulo_norm, candidato_norm)
        if score > melhor_score:
            melhor_score, melhor = score, candidato
    return melhor if melhor_score >= limiar else None

def openalex_por_doi(doi):
    if not doi:
        return None
    url = f'https://api.openalex.org/works/doi:{quote(doi, safe="")}'
    dados = api_get_json(url, params={'mailto': EMAIL_POLITE})
    if dados and isinstance(dados, dict) and dados.get('title'):
        return parse_openalex_work(dados)
    return None

def crossref_por_doi(doi):
    if not doi:
        return None
    url = f'https://api.crossref.org/works/{quote(doi, safe="")}'
    headers = {'User-Agent': f'RAGI-UFG/1.0 (mailto:{EMAIL_POLITE})'}
    dados = api_get_json(url, headers=headers)
    if dados and 'message' in dados:
        return parse_crossref_item(dados['message'])
    return None

def openalex_por_titulo(titulo, top=5):
    if not titulo:
        return None
    params = {'search': titulo, 'per-page': top, 'mailto': EMAIL_POLITE}
    dados = api_get_json('https://api.openalex.org/works', params=params)
    if not dados:
        return None
    candidatos = [parse_openalex_work(w) for w in dados.get('results', [])]
    return melhor_candidato(candidatos, titulo)

def crossref_por_titulo(titulo, top=5):
    if not titulo:
        return None
    headers = {'User-Agent': f'RAGI-UFG/1.0 (mailto:{EMAIL_POLITE})'}
    params = {
        'query.bibliographic': titulo,
        'rows': top,
        'select': 'DOI,title,abstract,subject,container-title,issued'
    }
    dados = api_get_json('https://api.crossref.org/works', params=params, headers=headers)
    if not dados or 'message' not in dados:
        return None
    candidatos = [parse_crossref_item(it) for it in dados['message'].get('items', [])]
    return melhor_candidato(candidatos, titulo)

print('✔ Funções de API carregadas')

"""# Célula 6 — Carregamento da base de entidades

"""

# ============================================================
# CÉLULA 6 — Carregar base de entidades
# ============================================================
# A classificação NÃO cria novas identidades: usa o ID_ENTIDADE
# já existente na base integrada / de entidades.
# ============================================================

if ARQUIVO_BASE_INTEGRADA:
    perfil_bruto = pd.read_excel(ARQUIVO_BASE_INTEGRADA)
    print('✔ Usando 03_base_integrada.xlsx')
elif ARQUIVO_ENTIDADES:
    perfil_bruto = pd.read_excel(ARQUIVO_ENTIDADES)
    print('✔ Usando 01_entidades.xlsx')
else:
    raise FileNotFoundError('Base de entidades não encontrada em BASE.')

COL_ENTIDADE = localizar_coluna(perfil_bruto, ['ID_ENTIDADE'])
COL_NOME     = localizar_coluna(perfil_bruto, ['NOME_CANONICO', 'NOME_ORIGINAL', 'Discente', 'Nome'])
COL_LATTES   = localizar_coluna(perfil_bruto, ['ID_LATTES_NORMALIZADO', 'ID_LATTES', 'ID_Lattes'])
COL_ORCID    = localizar_coluna(perfil_bruto, ['ORCID_NORMALIZADO', 'ORCID'])

if not COL_ENTIDADE:
    raise ValueError('Coluna ID_ENTIDADE não encontrada na base.')

if not COL_NOME:
    perfil_bruto['NOME_TMP'] = ''
    COL_NOME = 'NOME_TMP'
if not COL_LATTES:
    perfil_bruto['LATTES_TMP'] = ''
    COL_LATTES = 'LATTES_TMP'
if not COL_ORCID:
    perfil_bruto['ORCID_TMP'] = ''
    COL_ORCID = 'ORCID_TMP'

entidades = perfil_bruto.groupby(COL_ENTIDADE, dropna=False).agg({
    COL_NOME: 'first',
    COL_LATTES: 'first',
    COL_ORCID: 'first'
}).reset_index()

entidades.columns = ['ID_ENTIDADE', 'NOME_CANONICO', 'ID_LATTES', 'ORCID']
entidades['ID_ENTIDADE'] = entidades['ID_ENTIDADE'].fillna('').astype(str)
entidades['CHAVE_LATTES'] = entidades['ID_LATTES'].apply(normalizar_lattes)
entidades['CHAVE_ORCID']  = entidades['ORCID'].apply(normalizar_orcid)

entidades = entidades[entidades['ID_ENTIDADE'].str.strip() != '']
entidades = entidades.drop_duplicates(subset=['ID_ENTIDADE'])

print(f'✔ Entidades únicas       : {len(entidades)}')
print(f'✔ Entidades com ORCID    : {(entidades["CHAVE_ORCID"] != "").sum()}')
display(entidades.head())

"""# Célula 7 — Carregar títulos-alvo da planilha de egressos

"""

# ============================================================
# CÉLULA 7 — Carregar títulos-alvo (com limpeza de ruído)
# ============================================================

def padronizar_publicacoes(df, fonte):
    if df is None or df.empty:
        return pd.DataFrame()

    col_titulo = localizar_coluna(df, [
        'TITULO', 'Titulo', 'Titulo_Trabalho', 'Titulo_Tese',
        'Titulo_Dissertacao', 'Titulo_do_Trabalho', 'title', 'Título',
        'Tese', 'Dissertacao', 'Trabalho', 'Nome do Artigo', 'NOME_DO_ARTIGO'
    ])
    if not col_titulo:
        return pd.DataFrame()

    col_entidade  = localizar_coluna(df, ['ID_ENTIDADE'])
    col_nome      = localizar_coluna(df, ['NOME_CANONICO', 'Discente', 'Nome', 'NOME'])
    col_lattes    = localizar_coluna(df, ['ID_Lattes', 'ID_LATTES', 'ID_LATTES_NORMALIZADO'])
    col_orcid     = localizar_coluna(df, ['ORCID', 'ORCID_Egresso', 'ORCID_Lattes', 'ORCID_NORMALIZADO'])
    col_doi       = localizar_coluna(df, ['DOI', 'doi'])
    col_ano       = localizar_coluna(df, ['ANO', 'Ano', 'Year', 'Data_Publicacao', 'publication_year'])
    col_resumo    = localizar_coluna(df, ['RESUMO', 'Resumo', 'Abstract', 'abstract'])
    col_periodico = localizar_coluna(df, ['PERIODICO', 'Periodico', 'container-title', 'Veiculo'])
    col_ods       = localizar_coluna(df, ['ODS_ONU_Associados', 'ODS', 'SDG', 'ODS_OPENALEX'])

    out = pd.DataFrame()
    # APLICA A LIMPEZA DE TÍTULO AQUI
    out['TITULO']       = df[col_titulo].apply(limpar_titulo_ruido)
    out['ID_ENTIDADE']  = df[col_entidade].fillna('').astype(str) if col_entidade else ''
    out['NOME_CANONICO']= df[col_nome].fillna('').astype(str) if col_nome else ''
    out['CHAVE_LATTES'] = df[col_lattes].apply(normalizar_lattes) if col_lattes else ''
    out['CHAVE_ORCID']  = df[col_orcid].apply(normalizar_orcid) if col_orcid else ''
    out['DOI']          = df[col_doi].fillna('').astype(str) if col_doi else ''
    out['ANO']          = df[col_ano].fillna('').astype(str) if col_ano else ''
    out['RESUMO']       = df[col_resumo].fillna('').astype(str) if col_resumo else ''
    out['PERIODICO']    = df[col_periodico].fillna('').astype(str) if col_periodico else ''
    out['ODS_OPENALEX'] = df[col_ods].fillna('').astype(str) if col_ods else ''

    col_temas = localizar_coluna(df, [
        'TEMAS', 'Palavras_Chave_Conceitos', 'Topico_Principal',
        'Subcampo_Conhecimento', 'Campo_Conhecimento', 'Grande_Area_Conhecimento'
    ])
    if col_temas:
        out['TEMAS'] = df[col_temas].fillna('').astype(str)
    else:
        campos = [c for c in df.columns
                  if any(k in normalizar_texto(c) for k in
                         ['topico', 'subcampo', 'campo', 'grandearea',
                          'palavrachave', 'conceito', 'ods', 'assunto', 'keyword'])]
        out['TEMAS'] = combinar_campos_texto(df, campos) if campos else ''

    out['FONTE'] = fonte
    return out[out['TITULO'].str.strip() != '']

producoes_fontes = []
arquivo_usado = None

for candidato in CANDIDATOS_TITULOS:
    try:
        df_tmp = pd.read_excel(candidato)
    except Exception as e:
        print('✖ Erro ao ler', candidato.name, ':', e)
        continue
    pad = padronizar_publicacoes(df_tmp, f'Planilha: {candidato.name}')
    if not pad.empty:
        producoes_fontes.append(pad)
        arquivo_usado = candidato
        print('✔ Títulos carregados de:', candidato.name, '| linhas:', len(pad))
        break
    else:
        print('• Sem coluna de título útil:', candidato.name)

print('\n✔ Arquivo-fonte:', arquivo_usado if producoes_fontes else 'NENHUM')

"""# Célula 8 — Consolidar e deduplicar produções

"""

# ============================================================
# CÉLULA 8 — Consolidação inicial e deduplicação
# ============================================================

COLUNAS_PRODUCAO = [
    'ID_ENTIDADE', 'NOME_CANONICO', 'CHAVE_LATTES', 'CHAVE_ORCID',
    'TITULO', 'DOI', 'ANO', 'RESUMO', 'TEMAS', 'PERIODICO',
    'ODS_OPENALEX', 'FONTE'
]

todas_producoes = list(producoes_fontes)  # (produções via API serão adicionadas se ativadas)
producoes = pd.concat(todas_producoes, ignore_index=True, sort=False) if todas_producoes \
            else pd.DataFrame(columns=COLUNAS_PRODUCAO)

for coluna in COLUNAS_PRODUCAO:
    if coluna not in producoes.columns:
        producoes[coluna] = ''

producoes['CHAVE_LATTES'] = producoes['CHAVE_LATTES'].apply(normalizar_lattes)
producoes['CHAVE_ORCID']  = producoes['CHAVE_ORCID'].apply(normalizar_orcid)

# Mapas para preencher ID_ENTIDADE a partir de ORCID / Lattes / nome
mapa_lattes = (entidades[entidades['CHAVE_LATTES'] != '']
               .drop_duplicates('CHAVE_LATTES')
               .set_index('CHAVE_LATTES')['ID_ENTIDADE'].to_dict())
mapa_orcid  = (entidades[entidades['CHAVE_ORCID'] != '']
               .drop_duplicates('CHAVE_ORCID')
               .set_index('CHAVE_ORCID')['ID_ENTIDADE'].to_dict())
mapa_ent_nome = entidades.set_index('ID_ENTIDADE')['NOME_CANONICO'].to_dict()
mapa_nome_entidade = (
    entidades.assign(NOME_NORMALIZADO=entidades['NOME_CANONICO'].apply(normalizar_texto))
    .loc[lambda d: d['NOME_NORMALIZADO'] != '']
    .drop_duplicates('NOME_NORMALIZADO')
    .set_index('NOME_NORMALIZADO')['ID_ENTIDADE']
    .to_dict()
)

def preencher_entidade(row):
    if str(row.get('ID_ENTIDADE', '')).strip():
        return str(row['ID_ENTIDADE']).strip()
    orcid = normalizar_orcid(row.get('CHAVE_ORCID', ''))
    if orcid and orcid in mapa_orcid:
        return mapa_orcid[orcid]
    lattes = normalizar_lattes(row.get('CHAVE_LATTES', ''))
    if lattes and lattes in mapa_lattes:
        return mapa_lattes[lattes]
    nome_norm = normalizar_texto(row.get('NOME_CANONICO', ''))
    return mapa_nome_entidade.get(nome_norm, '')

producoes['ID_ENTIDADE'] = producoes.apply(preencher_entidade, axis=1)
producoes['NOME_CANONICO'] = producoes.apply(
    lambda r: r['NOME_CANONICO'] if str(r['NOME_CANONICO']).strip()
    else mapa_ent_nome.get(r['ID_ENTIDADE'], ''),
    axis=1
)

def preparar_chaves_producoes(df):
    df = df.copy()
    for coluna in COLUNAS_PRODUCAO:
        if coluna not in df.columns:
            df[coluna] = ''
    df['DOI_NORMALIZADO']    = df['DOI'].apply(normalizar_doi)
    df['TITULO_NORMALIZADO'] = df['TITULO'].apply(normalizar_texto)
    df['CHAVE_PUB'] = np.where(
        df['DOI_NORMALIZADO'] != '',
        'doi:' + df['DOI_NORMALIZADO'],
        'titulo:' + df['TITULO_NORMALIZADO']
    )
    df['SCORE_META'] = (
        df['TEMAS'].fillna('').astype(str).str.len() +
        df['RESUMO'].fillna('').astype(str).str.len() +
        df['ODS_OPENALEX'].fillna('').astype(str).str.len() +
        df['PERIODICO'].fillna('').astype(str).str.len() +
        df['DOI_NORMALIZADO'].fillna('').ne('').astype(int) * 500
    )
    return df

def deduplicar_producoes(df):
    if df.empty:
        return df.copy()
    df = preparar_chaves_producoes(df)
    df = df[df['TITULO_NORMALIZADO'] != '']
    if df.empty:
        return df
    return (df.sort_values(['SCORE_META', 'FONTE'], ascending=[False, True])
              .drop_duplicates('CHAVE_PUB')
              .reset_index(drop=True))

producoes = deduplicar_producoes(producoes)

print(f'✔ Produções únicas após deduplicação: {len(producoes)}')
display(producoes.head())

"""# Célula 9 — Enriquecimento via APIs (com cache e paralelismo)

"""

# ============================================================
# CÉLULA 9 — Enriquecimento por DOI ou título
# ============================================================
# - Usa cache em disco (permite parar e retomar).
# - Paraleliza com ThreadPoolExecutor (4 consultas simultâneas).
# ============================================================

from concurrent.futures import ThreadPoolExecutor, as_completed

USAR_PARALELO = True

# --- Cache ---
if ARQUIVO_CACHE.exists():
    with open(ARQUIVO_CACHE, 'r', encoding='utf-8') as f:
        cache_enriquecimento = json.load(f)
    print(f'✔ Cache carregado: {len(cache_enriquecimento)} entradas')
else:
    cache_enriquecimento = {}
    print('• Cache ainda não existe; será criado.')

def salvar_cache():
    with open(ARQUIVO_CACHE, 'w', encoding='utf-8') as f:
        json.dump(cache_enriquecimento, f, ensure_ascii=False)

def chave_cache(row):
    if row['DOI_NORMALIZADO']:
        return 'doi:' + row['DOI_NORMALIZADO']
    return 'titulo:' + row['TITULO_NORMALIZADO']

def enriquecer_um(tarefa):
    chave = tarefa['CHAVE_CACHE']
    if chave in cache_enriquecimento:
        return
    novo = None
    if tarefa['DOI_NORMALIZADO']:
        novo = (openalex_por_doi(tarefa['DOI_NORMALIZADO'])
                or crossref_por_doi(tarefa['DOI_NORMALIZADO']))
    elif tarefa['TITULO']:
        novo = (openalex_por_titulo(tarefa['TITULO'])
                or crossref_por_titulo(tarefa['TITULO']))
    cache_enriquecimento[chave] = novo if novo else {}

if USAR_ENRIQUECIMENTO_POR_TITULO and not producoes.empty:

    def precisa_enriquecer(row):
        return all(str(row.get(c, '')).strip() == ''
                   for c in ['TEMAS', 'RESUMO', 'ODS_OPENALEX'])

    selecao = producoes[producoes.apply(precisa_enriquecer, axis=1)]
    if MAX_ENRIQUECIMENTO_POR_TITULO:
        selecao = selecao.head(MAX_ENRIQUECIMENTO_POR_TITULO)

    tarefas = [{
        'INDICE': i,
        'CHAVE_CACHE': chave_cache(row),
        'DOI_NORMALIZADO': row['DOI_NORMALIZADO'],
        'TITULO': row['TITULO'],
    } for i, row in selecao.iterrows()]

    pendentes = [t for t in tarefas if t['CHAVE_CACHE'] not in cache_enriquecimento]
    print(f'Para enriquecer: {len(tarefas)} | '
          f'em cache: {len(tarefas) - len(pendentes)} | '
          f'pendentes: {len(pendentes)}')

    inicio = time.time()

    if USAR_PARALELO and pendentes:
        with ThreadPoolExecutor(max_workers=4) as pool:
            futuros = [pool.submit(enriquecer_um, t) for t in pendentes]
            for i, _ in enumerate(tqdm(as_completed(futuros),
                                       total=len(futuros),
                                       desc='Enriquecendo'), 1):
                if i % 25 == 0:
                    salvar_cache()
    else:
        for tarefa in tqdm(pendentes, desc='Enriquecendo'):
            enriquecer_um(tarefa)

    salvar_cache()

    # Aplica resultados do cache na base
    aplicados = 0
    for tarefa in tarefas:
        i = tarefa['INDICE']
        novo = cache_enriquecimento.get(tarefa['CHAVE_CACHE'], {})
        if not novo:
            continue
        for campo in ['DOI', 'ANO', 'RESUMO', 'TEMAS', 'PERIODICO', 'ODS_OPENALEX']:
            if novo.get(campo) and str(producoes.at[i, campo]).strip() == '':
                producoes.at[i, campo] = novo[campo]
                aplicados += 1

    print(f'✔ Campos preenchidos: {aplicados}')
    print(f'✔ Tempo total      : {time.time() - inicio:.0f}s')

    producoes = deduplicar_producoes(producoes)

print(f'✔ Produções após enriquecimento: {len(producoes)}')

"""# Célula 10 — Montar texto de análise

"""

# ============================================================
# CÉLULA 10 — Montar texto que será enviado ao classificador
# ============================================================

def montar_texto_analise(row):
    partes = []
    titulo = str(row.get('TITULO', '')).strip()
    if titulo:
        partes.append(titulo)
    temas = str(row.get('TEMAS', '')).strip()
    if temas:
        partes.append('temas: ' + temas[:500])
    resumo = str(row.get('RESUMO', '')).strip()
    if resumo:
        partes.append('resumo: ' + resumo[:800])
    periodico = str(row.get('PERIODICO', '')).strip()
    if periodico:
        partes.append('periódico: ' + periodico)
    return ' | '.join(partes)[:2000]

producoes['TEXTO_ANALISE'] = producoes.apply(montar_texto_analise, axis=1)
df_classificacao = producoes.copy()

print('✔ Texto de análise montado')
display(df_classificacao[['TITULO', 'TEXTO_ANALISE', 'ODS_OPENALEX']].head(10))

"""# Célula 10.5 Pré-classificação por palavras-chave"""

# ============================================================
# CÉLULA 10.5 — Pré-classificação por palavras-chave (item 2)
# ============================================================
# Serve como camada auxiliar: concordância com o Zero-Shot
# aumenta a confiança; divergência sinaliza necessidade de revisão.

REGRAS_ODS = {
    3:  ['saude', 'doenca', 'hospital', 'medic', 'enferm', 'covid', 'vacina', 'mental'],
    4:  ['educa', 'ensino', 'escola', 'pedagog', 'aprendiz', 'docen', 'curric'],
    5:  ['genero', 'mulher', 'femin', 'lgbt', 'homossex', 'sexualidade', 'machis'],
    8:  ['trabalho', 'emprego', 'renda', 'jornalis', 'profission', 'carreira'],
    10: ['desigualdade', 'vulnerab', 'exclusao', 'minor', 'perifer', 'pobre'],
    11: ['cidade', 'urban', 'mobilidade', 'territor', 'comunidade'],
    13: ['clima', 'ambient', 'sustentab', 'ecolog', 'carbono'],
    16: ['direito', 'justica', 'cidadania', 'politic', 'democra', 'jornalism'],
}

REGRAS_AREA = {
    'Ciências da Saúde': ['saude', 'doenca', 'hospital', 'medic'],
    'Ciências Humanas e Educação': ['educa', 'ensino', 'escola', 'filosof', 'sociolog'],
    'Ciências Sociais Aplicadas, Administração e Gestão da Informação':
        ['jornalism', 'comunica', 'midia', 'informa', 'gestao', 'marketing'],
    'Linguística, Letras e Artes':
        ['lingu', 'literat', 'cinema', 'arte', 'discurso', 'narrativ'],
}

def pre_classificar(texto):
    texto_norm = normalizar_texto(texto)
    ods_hits = [cod for cod, chaves in REGRAS_ODS.items()
                if any(k in texto_norm for k in chaves)]
    area_hits = [area for area, chaves in REGRAS_AREA.items()
                 if any(k in texto_norm for k in chaves)]
    return ods_hits, area_hits

pre = df_classificacao['TEXTO_ANALISE'].apply(pre_classificar)
df_classificacao['ODS_REGRA']  = pre.apply(lambda x: '; '.join(f'{c} {ODS_MAPA[c]}' for c in x[0]))
df_classificacao['AREA_REGRA'] = pre.apply(lambda x: '; '.join(x[1]))

print('✔ Pré-classificação por palavras-chave concluída')
display(df_classificacao[['TITULO', 'ODS_REGRA', 'AREA_REGRA']].head(10))

"""# Célula 11 — Classificação Zero-Shot

"""

# ============================================================
# CÉLULA 11 — Classificação Zero-Shot (com GPU, progresso e checkpoint)
# ============================================================

from transformers import pipeline
import torch
from tqdm.auto import tqdm

device = 0 if torch.cuda.is_available() else -1
if device == -1:
    print('⚠ ATENÇÃO: CPU detectada. Isso pode levar HORAS.')
    print('  Ambiente de execução → Alterar tipo → T4 GPU → Reiniciar sessão')
else:
    print('✔ Device: GPU')

classificador = pipeline(
    'zero-shot-classification',
    model='MoritzLaurer/mDeBERTa-v3-base-mnli-xnli',
    device=device
)

BATCH_SIZE = 8 if device == 0 else 4
SALVAR_A_CADA = 50

ARQ_CKPT_AREAS = PASTA_SAIDA / 'checkpoint_areas.json'
ARQ_CKPT_ODS   = PASTA_SAIDA / 'checkpoint_ods.json'

def carregar_ckpt(arq):
    if arq.exists():
        with open(arq, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {}

def salvar_ckpt(arq, d):
    with open(arq, 'w', encoding='utf-8') as f:
        json.dump(d, f, ensure_ascii=False)

def classificar_zeroshot(textos, labels, template, ckpt_arq,
                         batch_size=BATCH_SIZE, multi_label=True):
    cache = carregar_ckpt(ckpt_arq)
    resultados = [None] * len(textos)

    for i, txt in enumerate(textos):
        chave = str(hash((str(txt)[:200], template)))
        if chave in cache:
            resultados[i] = cache[chave]

    pendentes = [i for i, r in enumerate(resultados) if r is None]
    print(f'  → {len(textos)} textos | cache: {len(textos)-len(pendentes)} | pendentes: {len(pendentes)}')
    barra = tqdm(total=len(pendentes), desc='Classificando')

    for inicio in range(0, len(pendentes), batch_size):
        lote_idx = pendentes[inicio:inicio + batch_size]
        lote_txt = [str(textos[i])[:1000] for i in lote_idx]
        saida = classificador(lote_txt, labels, multi_label=multi_label,
                              hypothesis_template=template, truncation=True)
        if isinstance(saida, dict):
            saida = [saida]
        for i, r in zip(lote_idx, saida):
            resultados[i] = r
            cache[str(hash((str(textos[i])[:200], template)))] = r
        barra.update(len(lote_idx))
        if inicio > 0 and (inicio // batch_size) % (SALVAR_A_CADA // batch_size) == 0:
            salvar_ckpt(ckpt_arq, cache)

    barra.close()
    salvar_ckpt(ckpt_arq, cache)
    return resultados

# Inicializa colunas
for c in ['AREA_ZEROSHOT', 'AREAS_SECUNDARIAS', 'ODS_ZEROSHOT', 'ODS_ADERENTES_ZEROSHOT']:
    df_classificacao[c] = ''
df_classificacao['AREA_SCORE'] = np.nan
df_classificacao['ODS_SCORE']  = np.nan

mascara = df_classificacao['TITULO'].fillna('').astype(str).str.strip() != ''

if mascara.sum() > 0:
    textos = df_classificacao.loc[mascara, 'TEXTO_ANALISE'].fillna('').astype(str).tolist()
    textos = [t if t.strip() else 'sem informação' for t in textos]

    print('→ Classificando áreas (single-label)...')
    res_areas = classificar_zeroshot(
        textos, AREAS_LABELS,
        'Este trabalho acadêmico pertence à área {}.',
        ARQ_CKPT_AREAS, multi_label=False)   # ÁREA: single-label
    df_classificacao.loc[mascara, 'AREA_ZEROSHOT'] = [r['labels'][0] for r in res_areas]
    df_classificacao.loc[mascara, 'AREA_SCORE']    = [round(r['scores'][0], 4) for r in res_areas]
    df_classificacao.loc[mascara, 'AREAS_SECUNDARIAS'] = [
        '; '.join(f'{l} ({s:.2f})' for l, s in zip(r['labels'], r['scores'])
                  if s >= LIMIAR_AREAS_ADERENTES) for r in res_areas]

    print('→ Classificando ODS (multi-label)...')
    res_ods = classificar_zeroshot(
        textos, ODS_LABELS,
        'Este trabalho acadêmico contribui para o objetivo de desenvolvimento sustentável {}.',
        ARQ_CKPT_ODS, multi_label=True)
    df_classificacao.loc[mascara, 'ODS_ZEROSHOT'] = [
        formatar_rotulo_ods(r['labels'][0]) for r in res_ods]
    df_classificacao.loc[mascara, 'ODS_SCORE'] = [
        round(r['scores'][0], 4) for r in res_ods]
    df_classificacao.loc[mascara, 'ODS_ADERENTES_ZEROSHOT'] = [
        '; '.join(formatar_rotulo_ods(l) for l, s in zip(r['labels'], r['scores'])
                  if s >= LIMIAR_ODS_ADERENTES) for r in res_ods]
    print('✔ Classificação concluída.')
else:
    print('⚠ Nenhuma produção com título para classificar.')

"""# Célula 12 — Decisão final e confiança

"""

# ============================================================
# CÉLULA 12 — Decisão final, confiança dupla e concordância
# ============================================================

def decidir_ods(row):
    oa = str(row.get('ODS_OPENALEX', '')).strip()
    if oa:
        itens = [x.strip() for x in oa.split(';') if x.strip()]
        if itens:
            return pd.Series({'ODS_FINAL': itens[0], 'ODS_SCORE_FINAL': 1.0,
                              'ODS_FONTE': 'OpenAlex', 'ODS_ADERENTES': '; '.join(itens)})
    zs = row.get('ODS_ZEROSHOT', '')
    zs = '' if pd.isna(zs) else str(zs)
    score = row.get('ODS_SCORE', 0.0)
    score = 0.0 if pd.isna(score) else float(score)
    ad = row.get('ODS_ADERENTES_ZEROSHOT', '')
    ad = '' if pd.isna(ad) else str(ad)
    return pd.Series({'ODS_FINAL': zs, 'ODS_SCORE_FINAL': score,
                      'ODS_FONTE': 'ZeroShot', 'ODS_ADERENTES': ad})

if not df_classificacao.empty:
    df_classificacao = pd.concat(
        [df_classificacao, df_classificacao.apply(decidir_ods, axis=1)], axis=1)
else:
    for c in ['ODS_FINAL', 'ODS_SCORE_FINAL', 'ODS_FONTE', 'ODS_ADERENTES']:
        df_classificacao[c] = ''

df_classificacao['AREA_FINAL'] = df_classificacao.get('AREA_ZEROSHOT', '')
df_classificacao['AREA_FONTE'] = 'ZeroShot'

# ---- Confiança do modelo (só score) ----
def conf_modelo(score):
    score = float(score) if pd.notna(score) else 0.0
    if score >= 0.75: return 'alta'
    if score >= 0.50: return 'media'
    return 'baixa'

df_classificacao['CONF_MODELO_AREA'] = df_classificacao['AREA_SCORE'].apply(conf_modelo)
df_classificacao['CONF_MODELO_ODS']  = df_classificacao['ODS_SCORE_FINAL'].apply(conf_modelo)

# ---- Cobertura de evidência (tamanho do texto) ----
def cobertura(texto):
    t = len(str(texto))
    if t >= 500: return 'alta'
    if t >= 150: return 'media'
    return 'baixa'
df_classificacao['COBERTURA_EVIDENCIA'] = df_classificacao['TEXTO_ANALISE'].apply(cobertura)

# ---- Concordância OpenAlex × Zero-Shot ----
def concordancia_ods(row):
    oa = str(row.get('ODS_OPENALEX', '')).strip()
    zs = str(row.get('ODS_ZEROSHOT', '')).strip()
    if not oa or not zs:
        return 'sem_comparacao'
    m_oa = re.match(r'(\d+)', oa)
    m_zs = re.match(r'(\d+)', zs)
    if not m_oa or not m_zs:
        return 'sem_comparacao'
    return 'concordam' if m_oa.group(1) == m_zs.group(1) else 'divergem'

df_classificacao['CONCORDANCIA_ODS'] = df_classificacao.apply(concordancia_ods, axis=1)

# ---- Concordância com as regras de palavra-chave ----
def concordancia_regra(row):
    regras = str(row.get('ODS_REGRA', ''))
    if not regras.strip():
        return 'sem_regra'
    cod_regra = set(re.findall(r'\b(\d+)\s', regras))
    m_zs = re.match(r'(\d+)', str(row.get('ODS_ZEROSHOT', '')))
    if not cod_regra or not m_zs:
        return 'sem_regra'
    return 'reforca' if m_zs.group(1) in cod_regra else 'contraria'

df_classificacao['CONCORDANCIA_REGRA'] = df_classificacao.apply(concordancia_regra, axis=1)

# ---- Campo final de confiança: combina tudo ----
def confianca_final(row):
    conf_m = row.get('CONF_MODELO_ODS', 'baixa')
    regra  = row.get('CONCORDANCIA_REGRA', 'sem_regra')
    cob    = row.get('COBERTURA_EVIDENCIA', 'baixa')
    if conf_m == 'alta' and (regra == 'reforca' or cob == 'alta'):
        return 'alta'
    if conf_m == 'baixa' and regra == 'contraria':
        return 'revisar'
    return conf_m

df_classificacao['CONFIANCA_FINAL'] = df_classificacao.apply(confianca_final, axis=1)

print('✔ Decisão final calculada')
display(df_classificacao[['TITULO','AREA_FINAL','ODS_FINAL',
                          'CONF_MODELO_ODS','COBERTURA_EVIDENCIA',
                          'CONCORDANCIA_ODS','CONCORDANCIA_REGRA',
                          'CONFIANCA_FINAL']].head(10))

"""# Célula 13 — Consolidação por egresso

"""

# ============================================================
# CÉLULA 13 — Consolidação por ID_ENTIDADE (perfil analítico)
# ============================================================

def moda_texto(serie):
    v = serie.dropna().astype(str)
    v = v[v.str.strip() != '']
    return v.mode().iloc[0] if not v.empty else ''

def primeiro_texto(serie):
    v = [str(x).strip() for x in serie if str(x).strip()]
    return v[0] if v else ''

def unir_textos(serie):
    itens = set()
    for valor in serie:
        if pd.isna(valor): continue
        for p in str(valor).split(';'):
            p = p.strip()
            if p: itens.add(p)
    return '; '.join(sorted(itens))

def titulos_exemplo(serie, n=10):
    vistos = []
    for v in serie:
        v = str(v).strip()
        if v and v not in vistos: vistos.append(v)
        if len(vistos) >= n: break
    return ' | '.join(vistos)

def formatar_periodo(row):
    a, b = row['ANO_MIN'], row['ANO_MAX']
    if pd.isna(a) and pd.isna(b): return ''
    a_str = str(int(a)) if pd.notna(a) else ''
    b_str = str(int(b)) if pd.notna(b) else ''
    return f'{a_str}–{b_str}'.strip('–')

if not df_classificacao.empty:
    df_por_entidade = df_classificacao[
        df_classificacao['ID_ENTIDADE'].astype(str).str.strip() != ''
    ].copy()
else:
    df_por_entidade = pd.DataFrame()

if not df_por_entidade.empty:
    df_por_entidade['ANO_NUM'] = pd.to_numeric(df_por_entidade['ANO'], errors='coerce')

    classificacao_egressos = df_por_entidade.groupby('ID_ENTIDADE').agg(
        NOME_CANONICO=('NOME_CANONICO', primeiro_texto),
        TOTAL_PUBLICACOES=('TITULO', 'count'),
        ANO_MIN=('ANO_NUM', 'min'),
        ANO_MAX=('ANO_NUM', 'max'),
        AREA_PREDOMINANTE=('AREA_FINAL', moda_texto),
        AREA_SECUNDARIAS=('AREAS_SECUNDARIAS', unir_textos),
        ODS_PREDOMINANTE=('ODS_FINAL', moda_texto),
        ODS_TODOS=('ODS_ADERENTES', unir_textos),
        QTD_ODS_DISTINTOS=('ODS_ADERENTES',
                           lambda s: len([x for x in unir_textos(s).split(';') if x.strip()])),
        PUBLICACOES_ALTA_CONF=('CONF_MODELO_ODS', lambda s: int((s == 'alta').sum())),
        PUBLICACOES_BAIXA_CONF=('CONF_MODELO_ODS', lambda s: int((s == 'baixa').sum())),
        TITULOS_EXEMPLO=('TITULO', lambda x: titulos_exemplo(x, 10))
    ).reset_index()

    classificacao_egressos['PERIODO_ATUACAO'] = classificacao_egressos.apply(formatar_periodo, axis=1)
else:
    classificacao_egressos = pd.DataFrame(columns=[
        'ID_ENTIDADE','NOME_CANONICO','TOTAL_PUBLICACOES',
        'ANO_MIN','ANO_MAX','AREA_PREDOMINANTE','AREA_SECUNDARIAS',
        'ODS_PREDOMINANTE','ODS_TODOS','QTD_ODS_DISTINTOS',
        'PUBLICACOES_ALTA_CONF','PUBLICACOES_BAIXA_CONF',
        'TITULOS_EXEMPLO','PERIODO_ATUACAO'
    ])

print(f'✔ Egressos com produção classificada: {len(classificacao_egressos)}')
display(classificacao_egressos.head())

"""# Célula 14 — Resumo de qualidade

"""

# ============================================================
# CÉLULA 14 — Resumo de qualidade
# ============================================================

def contar_nao_vazio(df, coluna):
    if df.empty or coluna not in df.columns: return 0
    return int((df[coluna].fillna('').astype(str).str.strip() != '').sum())

def contar_valor(df, coluna, valor):
    if df.empty or coluna not in df.columns: return 0
    return int((df[coluna] == valor).sum())

resumo_qualidade = pd.DataFrame({
    'INDICADOR': [
        'Entidades carregadas',
        'Entidades com ORCID',
        'Produções únicas encontradas',
        'Produções com ID_ENTIDADE',
        'Produções com DOI',
        'Produções com resumo',
        'Produções com temas',
        'Produções com ODS vindo do OpenAlex',
        'Produções com confiança alta (ODS)',
        'Produções com confiança baixa (ODS)',
        'Produções marcadas como "revisar"',
        'Produções com cobertura alta de evidência',
        'Produções com cobertura baixa (só título)',
        'OpenAlex × Zero-Shot — concordam',
        'OpenAlex × Zero-Shot — divergem',
        'Regras × Zero-Shot — reforçam',
        'Regras × Zero-Shot — contrariam',
        'Egressos com produção classificada'
    ],
    'QUANTIDADE': [
        len(entidades),
        int((entidades['CHAVE_ORCID'] != '').sum()),
        len(df_classificacao),
        contar_nao_vazio(df_classificacao, 'ID_ENTIDADE'),
        contar_nao_vazio(df_classificacao, 'DOI_NORMALIZADO'),
        contar_nao_vazio(df_classificacao, 'RESUMO'),
        contar_nao_vazio(df_classificacao, 'TEMAS'),
        contar_nao_vazio(df_classificacao, 'ODS_OPENALEX'),
        contar_valor(df_classificacao, 'CONF_MODELO_ODS', 'alta'),
        contar_valor(df_classificacao, 'CONF_MODELO_ODS', 'baixa'),
        contar_valor(df_classificacao, 'CONFIANCA_FINAL', 'revisar'),
        contar_valor(df_classificacao, 'COBERTURA_EVIDENCIA', 'alta'),
        contar_valor(df_classificacao, 'COBERTURA_EVIDENCIA', 'baixa'),
        contar_valor(df_classificacao, 'CONCORDANCIA_ODS', 'concordam'),
        contar_valor(df_classificacao, 'CONCORDANCIA_ODS', 'divergem'),
        contar_valor(df_classificacao, 'CONCORDANCIA_REGRA', 'reforca'),
        contar_valor(df_classificacao, 'CONCORDANCIA_REGRA', 'contraria'),
        len(classificacao_egressos)
    ]
})

display(resumo_qualidade)

"""# Célula 15 — Base de validação humana

"""

# ============================================================
# CÉLULA 15 — Amostra de validação estratificada
# ============================================================
# Garante que os casos difíceis (baixa confiança, divergência)
# entrem na revisão — não só os fáceis.

N_POR_ESTRATO = 25

def amostra_estratificada(df):
    if df.empty:
        return df.copy()
    partes = []
    partes.append(df[(df['CONF_MODELO_AREA'] == 'alta') &
                     (df['CONF_MODELO_ODS']  == 'alta')].head(N_POR_ESTRATO))
    partes.append(df[(df['CONF_MODELO_AREA'] == 'baixa') |
                     (df['CONF_MODELO_ODS']  == 'baixa')].head(N_POR_ESTRATO))
    partes.append(df[df['CONCORDANCIA_ODS'] == 'divergem'].head(N_POR_ESTRATO))
    partes.append(df[df['CONCORDANCIA_REGRA'] == 'contraria'].head(N_POR_ESTRATO))
    partes.append(df.sample(min(N_POR_ESTRATO, len(df)), random_state=42))
    return (pd.concat(partes)
              .drop_duplicates(subset=['TITULO'])
              .reset_index(drop=True))

colunas_validacao = [
    'ID_ENTIDADE','NOME_CANONICO','TITULO','ANO',
    'AREA_FINAL','AREA_SCORE','CONF_MODELO_AREA',
    'ODS_FINAL','ODS_SCORE_FINAL','ODS_FONTE','CONF_MODELO_ODS',
    'COBERTURA_EVIDENCIA','CONCORDANCIA_ODS','CONCORDANCIA_REGRA',
    'CONFIANCA_FINAL','TEXTO_ANALISE'
]

if not df_classificacao.empty:
    validacao = amostra_estratificada(df_classificacao)[colunas_validacao].copy()
else:
    validacao = pd.DataFrame(columns=colunas_validacao)

validacao['AVALIACAO_HUMANA'] = ''
validacao['JUSTIFICATIVA']    = ''
validacao['OBSERVACAO']       = ''

print(f'✔ Amostra de validação: {len(validacao)} linhas (estratificada)')
display(validacao.head())

"""# Célula 15.5 — Painéis de distribuição (NOVA)

"""

# ============================================================
# CÉLULA 15.5 — Painéis de distribuição (ODS e Área)
# ============================================================

def explodir_multirrotulo(df, coluna, nome_novo):
    linhas = []
    for _, row in df.iterrows():
        valor = str(row.get(coluna, '') or '')
        for item in valor.split(';'):
            item = item.strip()
            if item:
                linhas.append({
                    'ID_ENTIDADE': row.get('ID_ENTIDADE', ''),
                    nome_novo: item,
                    'ANO': row.get('ANO', ''),
                    'TITULO': row.get('TITULO', '')
                })
    return pd.DataFrame(linhas)

# Distribuição por ODS
df_ods_expl = explodir_multirrotulo(df_classificacao, 'ODS_ADERENTES', 'ODS')
if not df_ods_expl.empty:
    distribuicao_ods = (df_ods_expl.groupby('ODS')
        .agg(PRODUCOES=('TITULO', 'count'),
             EGRESSOS=('ID_ENTIDADE', 'nunique'))
        .reset_index().sort_values('PRODUCOES', ascending=False))
else:
    distribuicao_ods = pd.DataFrame(columns=['ODS','PRODUCOES','EGRESSOS'])

# Distribuição por área
df_area_expl = explodir_multirrotulo(df_classificacao, 'AREA_FINAL', 'AREA')
if not df_area_expl.empty:
    distribuicao_area = (df_area_expl.groupby('AREA')
        .agg(PRODUCOES=('TITULO', 'count'),
             EGRESSOS=('ID_ENTIDADE', 'nunique'))
        .reset_index().sort_values('PRODUCOES', ascending=False))
else:
    distribuicao_area = pd.DataFrame(columns=['AREA','PRODUCOES','EGRESSOS'])

# Matriz ODS × Ano
matriz_ods_ano = pd.DataFrame()
if not df_ods_expl.empty:
    df_tmp = df_ods_expl.copy()
    df_tmp['ANO_NUM'] = pd.to_numeric(df_tmp['ANO'], errors='coerce')
    df_tmp = df_tmp.dropna(subset=['ANO_NUM'])
    if not df_tmp.empty:
        matriz_ods_ano = df_tmp.pivot_table(
            index='ODS', columns='ANO_NUM', values='TITULO',
            aggfunc='count', fill_value=0)

print('✔ Distribuição por ODS:')
display(distribuicao_ods.head(20))
print('\n✔ Distribuição por Área:')
display(distribuicao_area)
print('\n✔ Matriz ODS × Ano (visualização resumida):')
display(matriz_ods_ano.head())

"""# Célula 15.7 — Explicabilidade por palavras-chave"""

# ============================================================
# CÉLULA 15.7 — Explicabilidade por palavras-chave
# ============================================================

PALAVRAS_ODS = {
    '1 Erradicação da pobreza': ['pobre', 'miseria', 'renda minima'],
    '2 Fome zero e agricultura sustentável': ['fome', 'agricultura', 'aliment'],
    '3 Saúde e bem-estar': ['saude', 'doenca', 'hospital', 'medic', 'mental'],
    '4 Educação de qualidade': ['educa', 'ensino', 'escola', 'pedagog'],
    '5 Igualdade de gênero': ['genero', 'mulher', 'femin', 'lgbt'],
    '6 Água potável e saneamento': ['agua', 'saneamento', 'esgoto'],
    '7 Energia limpa e acessível': ['energia', 'renovav', 'solar', 'eolic'],
    '8 Trabalho decente e crescimento econômico': ['trabalho', 'emprego', 'renda'],
    '9 Indústria, inovação e infraestrutura': ['industri', 'inova', 'infraestrutur'],
    '10 Redução das desigualdades': ['desigualdade', 'vulnerab', 'exclusao'],
    '11 Cidades e comunidades sustentáveis': ['cidade', 'urban', 'mobilidade'],
    '12 Consumo e produção responsáveis': ['consumo', 'producao', 'recicla'],
    '13 Ação contra a mudança global do clima': ['clima', 'ambient', 'carbono'],
    '14 Vida na água': ['agua', 'marinho', 'ocean', 'pesca'],
    '15 Vida terrestre': ['floresta', 'biodivers', 'terrestre', 'fauna'],
    '16 Paz, justiça e instituições eficazes': ['direito', 'justica', 'cidadania', 'democra'],
    '17 Parcerias e meios de implementação': ['parceria', 'cooperacao', 'rede'],
}

def explicar_ods(row):
    texto = normalizar_texto(row.get('TEXTO_ANALISE', ''))
    ods = str(row.get('ODS_FINAL', '')).strip()
    chaves = PALAVRAS_ODS.get(ods, [])
    hits = [k for k in chaves if k in texto]
    return ', '.join(hits) if hits else '(sem palavra-chave explícita)'

df_classificacao['EXPLICACAO_ODS'] = df_classificacao.apply(explicar_ods, axis=1)

print('✔ Explicabilidade calculada')
display(df_classificacao[['TITULO','ODS_FINAL','EXPLICACAO_ODS']].head(10))

"""# Célula 16 — Exportação

"""

# ============================================================
# CÉLULA 16 — Exportação completa
# ============================================================

def truncar_texto(valor, limite=30000):
    if pd.isna(valor): return ''
    return str(valor)[:limite]

def preparar_para_excel(df):
    df = df.copy()
    for c in df.columns:
        if df[c].dtype == 'object':
            df[c] = df[c].map(truncar_texto)
    return df

# Caminhos
ARQ_PRODUCOES     = PASTA_SAIDA / '01_producoes_capturadas.xlsx'
ARQ_CLASSIFICADAS = PASTA_SAIDA / '02_producoes_classificadas.xlsx'
ARQ_EGRESSOS      = PASTA_SAIDA / '03_classificacao_por_egresso.xlsx'
ARQ_VALIDACAO     = PASTA_SAIDA / '04_validacao_humana.xlsx'
ARQ_RESUMO        = PASTA_SAIDA / '05_resumo_qualidade.xlsx'
ARQ_DIST_ODS      = PASTA_SAIDA / '06_distribuicao_ods.xlsx'
ARQ_DIST_AREA     = PASTA_SAIDA / '07_distribuicao_area.xlsx'
ARQ_MATRIZ_ANO    = PASTA_SAIDA / '08_matriz_ods_ano.xlsx'
ARQ_UNICO         = PASTA_SAIDA / '00_classificacao_completa.xlsx'

# XLSX individuais
preparar_para_excel(producoes).to_excel(ARQ_PRODUCOES, index=False)
preparar_para_excel(df_classificacao).to_excel(ARQ_CLASSIFICADAS, index=False)
preparar_para_excel(classificacao_egressos).to_excel(ARQ_EGRESSOS, index=False)
preparar_para_excel(validacao).to_excel(ARQ_VALIDACAO, index=False)
resumo_qualidade.to_excel(ARQ_RESUMO, index=False)
distribuicao_ods.to_excel(ARQ_DIST_ODS, index=False)
distribuicao_area.to_excel(ARQ_DIST_AREA, index=False)
if not matriz_ods_ano.empty:
    matriz_ods_ano.to_excel(ARQ_MATRIZ_ANO)

# CSV e Parquet (para dashboards)
try:
    df_classificacao.to_csv(ARQ_CLASSIFICADAS.with_suffix('.csv'),
                            index=False, encoding='utf-8-sig')
    df_classificacao.to_parquet(ARQ_CLASSIFICADAS.with_suffix('.parquet'), index=False)
    classificacao_egressos.to_csv(ARQ_EGRESSOS.with_suffix('.csv'),
                                  index=False, encoding='utf-8-sig')
    print('✔ CSV e Parquet exportados')
except Exception as e:
    print('⚠ CSV/Parquet não gerados:', e)

# Excel único multi-aba (item 11)
try:
    with pd.ExcelWriter(ARQ_UNICO, engine='openpyxl') as writer:
        preparar_para_excel(producoes).to_excel(writer, sheet_name='Producoes', index=False)
        preparar_para_excel(df_classificacao).to_excel(writer, sheet_name='Classificadas', index=False)
        preparar_para_excel(classificacao_egressos).to_excel(writer, sheet_name='Por_Egresso', index=False)
        distribuicao_ods.to_excel(writer, sheet_name='Distribuicao_ODS', index=False)
        distribuicao_area.to_excel(writer, sheet_name='Distribuicao_Area', index=False)
        resumo_qualidade.to_excel(writer, sheet_name='Qualidade', index=False)
        validacao.to_excel(writer, sheet_name='Validacao_Humana', index=False)
        if not matriz_ods_ano.empty:
            matriz_ods_ano.to_excel(writer, sheet_name='Matriz_ODS_Ano')
    print('✔ Arquivo único multi-aba gerado')
except Exception as e:
    print('⚠ Arquivo único não gerado:', e)

print('\n✔ Arquivos salvos em:', PASTA_SAIDA)
for arq in sorted(PASTA_SAIDA.glob('*')):
    print('  -', arq.name)