# -*- coding: utf-8 -*-
"""modulo_normalizacao_desambiguacao_egressos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1twASAJMqUZMWubxP-FjiIA_vhXkSBNTf

# Módulo — Normalização e Desambiguação de Entidades

## Integração de egressos e publicações

### Objetivo

Este notebook implementa a etapa de **normalização e desambiguação de entidades**.

A finalidade é transformar registros provenientes de diferentes fontes em uma estrutura integrada, na qual cada egresso possua uma **entidade única (`ID_ENTIDADE`)**.

Neste módulo, as bases de **OpenAlex** e **Crossref** são utilizadas como fontes de publicações e informações de identificação. Os identificadores `ID_Lattes` e `ORCID` são priorizados como evidências de identidade, enquanto a normalização e a similaridade dos nomes funcionam como mecanismos complementares.

### Problema que o módulo resolve

Um mesmo egresso pode aparecer com pequenas diferenças entre as fontes:

- `Ana Júlia de Freitas Carrijo`
- `ANA JULIA DE FREITAS CARRIJO`
- `Ana Júlia de Freitas Carrijo`
- `Ana J. de Freitas Carrijo`

O algoritmo deve reconhecer que esses registros podem representar a mesma pessoa, sem apagar o nome original.

### Princípio central

O módulo **não substitui os dados originais**. Ele cria campos padronizados e uma chave de integração.

A relação conceitual é:

```text
                 FONTES DE DADOS
                      │
        ┌─────────────┴─────────────┐
        ↓                           ↓
     OpenAlex                    Crossref
        │                           │
        └─────────────┬─────────────┘
                      ↓
              NORMALIZAÇÃO
                      ↓
             DESAMBIGUAÇÃO
                      ↓
               ID_ENTIDADE
                      ↓
             BASE INTEGRADA
```

O `ID_ENTIDADE` será posteriormente utilizado para relacionar produção científica, informações acadêmicas e outras fontes do projeto.

## 1. Estrutura das relações

O modelo adotado neste notebook separa três conceitos:

### 1.1 Entidade

Representa a **pessoa**, independentemente da fonte.

Exemplo:

```text
ENT000001 → Ana Júlia de Freitas Carrijo
```

### 1.2 Registro de fonte

Representa como essa pessoa aparece em uma determinada base.

```text
ENT000001 → OpenAlex
ENT000001 → Crossref
```

### 1.3 Publicação

Representa um trabalho associado ao registro da pessoa.

```text
ENT000001
   ├── publicação OpenAlex A
   ├── publicação OpenAlex B
   └── publicação Crossref A
```

Assim, uma pessoa pode ter **muitos registros e muitas publicações**, mas continua sendo uma única entidade.

### Regra de integração

```text
ID_ENTIDADE
    │
    ├── ID_LATTES
    ├── ORCID
    ├── nomes encontrados
    ├── registros OpenAlex
    └── registros Crossref
```

Essa estrutura evita usar o nome como chave principal. O nome é um atributo textual sujeito a variações; `ID_Lattes` e `ORCID`, quando presentes e consistentes, são evidências muito mais fortes.

## 2. Importação das bibliotecas

As bibliotecas abaixo são utilizadas para:

- leitura e escrita das planilhas;
- manipulação das tabelas;
- normalização textual;
- cálculo de similaridade entre nomes;
- identificação de grupos de registros.
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path
!pip install rapidfuzz
from rapidfuzz import fuzz

"""## 3. Definição dos arquivos de entrada e saída

As planilhas utilizadas neste módulo são:

- `publicacoes_egressos_openalex.xlsx`
- `publicacoes_crossref_lattes.xlsx`

Elas representam resultados dos módulos de enriquecimento científico.

### Importante

Os arquivos de entrada permanecem intactos. O notebook somente lê essas bases e produz novos arquivos estruturados.

A pasta de saída concentra os resultados do módulo para facilitar a rastreabilidade e a integração posterior.
"""

# pasta onde estão as bases utilizadas pelo módulo
PASTA_BASE = Path("/content/drive/MyDrive/RAGI 2026 2")

# arquivos de entrada
ARQUIVO_OPENALEX = PASTA_BASE / "Enriquecimento de dados - OPENALEX" / "Estratégia 1" / "publicacoes_egressos_openalex.xlsx"
ARQUIVO_CROSSREF = PASTA_BASE / "Enriquecimento de dados - CROSSREF" / "Estratégia 1" / "publicacoes_crossref_lattes.xlsx"

# pasta de saída deste módulo
PASTA_SAIDA = PASTA_BASE / "Modulo II" / "Desambiguação de entidades"
PASTA_SAIDA.mkdir(parents=True, exist_ok=True)

print("OpenAlex:", ARQUIVO_OPENALEX)
print("Crossref:", ARQUIVO_CROSSREF)
print("Saída:", PASTA_SAIDA)

"""## 4. Leitura das planilhas

Nesta etapa carregamos as duas fontes sem alterar seus dados.

A primeira inspeção é necessária porque o algoritmo deve trabalhar com os nomes reais das colunas presentes nos arquivos.
"""

openalex = pd.read_excel(ARQUIVO_OPENALEX)
crossref = pd.read_excel(ARQUIVO_CROSSREF)

print("OpenAlex:", openalex.shape)
print("Crossref:", crossref.shape)

print("\nColunas OpenAlex:")
print(openalex.columns.tolist())

print("\nColunas Crossref:")
print(crossref.columns.tolist())

"""## 5. Inspeção das informações de identificação

Antes da normalização, verificamos quais campos podem identificar um egresso.

Neste projeto, os principais campos são:

- nome do discente;
- `ID_Lattes`;
- `ORCID`.

A existência desses campos permite construir uma estratégia de desambiguação baseada em evidências, em vez de depender somente da comparação textual dos nomes.
"""

def mostrar_colunas_identificacao(df, nome_base):
    possiveis = [
        "Discente", "Discente_Lattes",
        "ID_Lattes",
        "ORCID", "ORCID_Lattes"
    ]

    existentes = [c for c in possiveis if c in df.columns]

    print(f"\n{nome_base}")
    print("Campos encontrados:", existentes)

    if existentes:
        display(df[existentes].head())

mostrar_colunas_identificacao(openalex, "OpenAlex")
mostrar_colunas_identificacao(crossref, "Crossref")

"""## 6. Padronização dos nomes das colunas

As fontes podem utilizar nomes diferentes para representar o mesmo conceito.

Por isso, criamos uma representação interna comum:

```text
NOME
ID_LATTES
ORCID
```

O nome original continua preservado em uma coluna específica quando necessário.
"""

def preparar_colunas(df, fonte):
    df = df.copy()

    if fonte == "OpenAlex":
        if "Discente_Lattes" in df.columns:
            df["NOME_ORIGINAL"] = df["Discente_Lattes"]
        elif "Discente" in df.columns:
            df["NOME_ORIGINAL"] = df["Discente"]

        if "ORCID_Lattes" in df.columns:
            df["ORCID"] = df["ORCID_Lattes"]

    elif fonte == "Crossref":
        if "Discente" in df.columns:
            df["NOME_ORIGINAL"] = df["Discente"]

    if "ID_Lattes" not in df.columns:
        df["ID_Lattes"] = pd.NA

    if "ORCID" not in df.columns:
        df["ORCID"] = pd.NA

    df["FONTE"] = fonte

    return df

openalex_pad = preparar_colunas(openalex, "OpenAlex")
crossref_pad = preparar_colunas(crossref, "Crossref")

print("OpenAlex preparado:", openalex_pad.shape)
print("Crossref preparado:", crossref_pad.shape)

"""## 7. Normalização do nome

A normalização cria uma versão comparável do nome.

### O que é alterado

- conversão para texto;
- remoção de espaços nas extremidades;
- remoção de acentos;
- conversão para minúsculas;
- remoção de pontuação;
- redução de espaços duplicados.

### O que não é alterado

O nome original permanece disponível.

Exemplo:

```text
Original:
Ana Júlia de Freitas Carrijo

Normalizado:
ana julia de freitas carrijo
```

A normalização serve para **comparação**. Ela não deve ser utilizada como substituta do nome oficial da pessoa.
"""

def remover_acentos(texto):
    texto = unicodedata.normalize("NFKD", str(texto))
    return "".join(
        caractere for caractere in texto
        if not unicodedata.combining(caractere)
    )

def normalizar_nome(nome):
    if pd.isna(nome):
        return ""

    nome = str(nome).strip().lower()
    nome = remover_acentos(nome)
    nome = re.sub(r"[^a-z0-9\s]", " ", nome)
    nome = re.sub(r"\s+", " ", nome).strip()

    return nome

openalex_pad["NOME_NORMALIZADO"] = openalex_pad["NOME_ORIGINAL"].apply(normalizar_nome)
crossref_pad["NOME_NORMALIZADO"] = crossref_pad["NOME_ORIGINAL"].apply(normalizar_nome)

display(openalex_pad[["NOME_ORIGINAL", "NOME_NORMALIZADO"]].drop_duplicates().head(10))

"""## 8. Normalização do ID Lattes

O identificador Lattes pode aparecer com diferentes formatos de representação.

A função abaixo mantém somente os caracteres numéricos.

Isso permite comparar, por exemplo:

```text
948153683101920
http://lattes.cnpq.br/948153683101920
Lattes: 948153683101920
```

como o mesmo identificador.

O valor original não é descartado.
"""

def normalizar_lattes(valor):
    if pd.isna(valor):
        return ""

    valor = str(valor)
    numeros = re.sub(r"\D", "", valor)

    return numeros

openalex_pad["ID_LATTES_NORMALIZADO"] = openalex_pad["ID_Lattes"].apply(normalizar_lattes)
crossref_pad["ID_LATTES_NORMALIZADO"] = crossref_pad["ID_Lattes"].apply(normalizar_lattes)

"""## 9. Normalização do ORCID

O ORCID também pode aparecer como:

```text
0000-0001-8372-1003
https://orcid.org/0000-0001-8372-1003
ORCID: 0000-0001-8372-1003
```

A comparação será feita utilizando apenas o identificador padronizado.
"""

def normalizar_orcid(valor):
    if pd.isna(valor):
        return ""

    valor = str(valor).strip()
    valor = re.sub(r"^https?://orcid\.org/", "", valor, flags=re.IGNORECASE)
    valor = re.sub(r"^orcid:\s*", "", valor, flags=re.IGNORECASE)

    return valor.strip()

openalex_pad["ORCID_NORMALIZADO"] = openalex_pad["ORCID"].apply(normalizar_orcid)
crossref_pad["ORCID_NORMALIZADO"] = crossref_pad["ORCID"].apply(normalizar_orcid)

"""## 10. Consolidação dos registros das fontes

Agora as duas bases possuem uma estrutura mínima comum.

A partir deste ponto, cada linha representa um **registro de uma fonte**, e não necessariamente uma entidade única.

Isso é importante porque uma mesma pessoa pode aparecer muitas vezes devido às suas várias publicações.

Portanto:

```text
1 pessoa
   ↓
vários registros OpenAlex
   ↓
vários registros Crossref
```

O algoritmo primeiro precisa identificar a pessoa e somente depois relacionar suas publicações.
"""

registros = pd.concat(
    [openalex_pad, crossref_pad],
    ignore_index=True,
    sort=False
)

registros["ID_REGISTRO"] = [
    f"REG{numero:06d}"
    for numero in range(1, len(registros) + 1)
]

colunas_base = [
    "ID_REGISTRO",
    "FONTE",
    "NOME_ORIGINAL",
    "NOME_NORMALIZADO",
    "ID_Lattes",
    "ID_LATTES_NORMALIZADO",
    "ORCID",
    "ORCID_NORMALIZADO"
]

colunas_base = [c for c in colunas_base if c in registros.columns]

display(registros[colunas_base].head())

"""## 11. Criação das entidades

Uma entidade representa uma pessoa única.

### Ordem de confiança

A estratégia utilizada é:

1. `ID_Lattes` igual → forte evidência de mesma pessoa;
2. `ORCID` igual → forte evidência de mesma pessoa;
3. nome normalizado igual → evidência textual forte;
4. nome semelhante → gera candidato para análise;
5. conflito entre identificadores → não agrupar automaticamente.

### Por que não usar somente o nome?

Porque homônimos são possíveis.

Exemplo:

```text
Maria Silva
```

pode representar pessoas diferentes.

Por isso, a similaridade textual é utilizada como apoio e não como prova isolada.
"""

# estrutura inicial para as entidades
entidades = []

# índices para localizar entidades já criadas
indice_lattes = {}
indice_orcid = {}
indice_nome = {}

def novo_id_entidade(numero):
    return f"ENT{numero:06d}"

def adicionar_entidade(registro, numero):
    entidade = {
        "ID_ENTIDADE": novo_id_entidade(numero),
        "NOME_CANONICO": registro["NOME_ORIGINAL"],
        "NOME_NORMALIZADO": registro["NOME_NORMALIZADO"],
        "ID_LATTES": registro["ID_LATTES_NORMALIZADO"],
        "ORCID": registro["ORCID_NORMALIZADO"],
    }

    entidades.append(entidade)
    return entidade

"""## 12. Desambiguação determinística por identificadores

Nesta etapa usamos os identificadores disponíveis.

### Regra

Se um registro possui `ID_Lattes` e ele já está associado a uma entidade, o registro será relacionado àquela entidade.

O mesmo ocorre para o ORCID.

### Conflito

Se Lattes aponta para uma entidade e ORCID aponta para outra, o algoritmo **não deve escolher arbitrariamente**.

Esse caso será enviado para revisão.
"""

def encontrar_por_identificador(registro):
    lattes = registro["ID_LATTES_NORMALIZADO"]
    orcid = registro["ORCID_NORMALIZADO"]

    entidade_lattes = indice_lattes.get(lattes) if lattes else None
    entidade_orcid = indice_orcid.get(orcid) if orcid else None

    if entidade_lattes and entidade_orcid and entidade_lattes != entidade_orcid:
        return None, "CONFLITO_IDENTIFICADORES"

    if entidade_lattes:
        return entidade_lattes, "ID_LATTES"

    if entidade_orcid:
        return entidade_orcid, "ORCID"

    return None, "SEM_IDENTIFICADOR"

"""## 13. Similaridade entre nomes

Quando não existe um identificador suficiente para resolver a identidade, comparamos os nomes.

A métrica utilizada é o `token_set_ratio` do RapidFuzz.

A vantagem dessa abordagem é que pequenas diferenças na ordem ou repetição de palavras podem ser toleradas.

O resultado varia de 0 a 100:

```text
100 → nomes muito semelhantes
  0 → nomes completamente diferentes
```

O score não significa, sozinho, que duas pessoas são a mesma pessoa.
"""

def similaridade_nomes(nome_a, nome_b):
    if not nome_a or not nome_b:
        return 0

    return fuzz.token_set_ratio(nome_a, nome_b)

def melhor_entidade_por_nome(registro, entidades_df, limite=90):
    melhor_id = None
    melhor_score = 0

    for _, entidade in entidades_df.iterrows():
        score = similaridade_nomes(
            registro["NOME_NORMALIZADO"],
            entidade["NOME_NORMALIZADO"]
        )

        if score > melhor_score:
            melhor_score = score
            melhor_id = entidade["ID_ENTIDADE"]

    if melhor_score >= limite:
        return melhor_id, melhor_score

    return None, melhor_score

"""## 14. Processamento das entidades

Agora combinamos as regras.

### Resultado possível

- `AUTOMATICA_ID_LATTES`
- `AUTOMATICA_ORCID`
- `AUTOMATICA_NOME`
- `REVISAO_MANUAL`
- `NOVA_ENTIDADE`

A decisão é registrada para manter a explicabilidade do algoritmo.
"""

entidades_df = pd.DataFrame(
    columns=[
        "ID_ENTIDADE",
        "NOME_CANONICO",
        "NOME_NORMALIZADO",
        "ID_LATTES",
        "ORCID"
    ]
)

resultados = []
contador_entidades = 0

for _, registro in registros.iterrows():

    entidade_id, metodo = encontrar_por_identificador(registro)

    if metodo == "CONFLITO_IDENTIFICADORES":
        contador_entidades += 1
        entidade = adicionar_entidade(registro, contador_entidades)

        resultados.append({
            "ID_REGISTRO": registro["ID_REGISTRO"],
            "ID_ENTIDADE": entidade["ID_ENTIDADE"],
            "METODO": "REVISAO_MANUAL",
            "SCORE_NOME": np.nan,
            "STATUS": "REVISAO_MANUAL"
        })

        continue

    if entidade_id:
        resultados.append({
            "ID_REGISTRO": registro["ID_REGISTRO"],
            "ID_ENTIDADE": entidade_id,
            "METODO": metodo,
            "SCORE_NOME": 100,
            "STATUS": "AUTOMATICO"
        })

        continue

    entidades_df = pd.DataFrame(entidades)

    if len(entidades_df) > 0:
        entidade_nome, score = melhor_entidade_por_nome(
            registro,
            entidades_df,
            limite=95
        )
    else:
        entidade_nome, score = None, 0

    if entidade_nome:
        resultados.append({
            "ID_REGISTRO": registro["ID_REGISTRO"],
            "ID_ENTIDADE": entidade_nome,
            "METODO": "NOME_NORMALIZADO",
            "SCORE_NOME": score,
            "STATUS": "AUTOMATICO"
        })

        continue

    contador_entidades += 1
    entidade = adicionar_entidade(registro, contador_entidades)

    resultados.append({
        "ID_REGISTRO": registro["ID_REGISTRO"],
        "ID_ENTIDADE": entidade["ID_ENTIDADE"],
        "METODO": "NOVA_ENTIDADE",
        "SCORE_NOME": score,
        "STATUS": "NOVA_ENTIDADE"
    })

    # atualiza índices
    if entidade["ID_LATTES"]:
        indice_lattes[entidade["ID_LATTES"]] = entidade["ID_ENTIDADE"]

    if entidade["ORCID"]:
        indice_orcid[entidade["ORCID"]] = entidade["ID_ENTIDADE"]

    if entidade["NOME_NORMALIZADO"]:
        indice_nome[entidade["NOME_NORMALIZADO"]] = entidade["ID_ENTIDADE"]

mapa_registros = pd.DataFrame(resultados)
entidades_df = pd.DataFrame(entidades)

print("Entidades criadas:", len(entidades_df))
print("Registros processados:", len(mapa_registros))

"""## 15. Atualização da base de entidades

A entidade é criada inicialmente a partir do primeiro registro encontrado.

Quando outros registros são relacionados a ela, podemos enriquecer a entidade com identificadores que ainda estejam ausentes.

Isso evita perder informação quando, por exemplo:

```text
Registro OpenAlex
nome + ORCID

Registro Crossref
nome + ID_Lattes
```

estão relacionados à mesma pessoa.
"""

for _, linha in mapa_registros.iterrows():
    id_entidade = linha["ID_ENTIDADE"]

    registros_entidade = registros[
        registros["ID_REGISTRO"] == linha["ID_REGISTRO"]
    ]

    if registros_entidade.empty:
        continue

    registro = registros_entidade.iloc[0]

    indice = entidades_df.index[
        entidades_df["ID_ENTIDADE"] == id_entidade
    ]

    if len(indice) == 0:
        continue

    i = indice[0]

    if not entidades_df.at[i, "ID_LATTES"]:
        entidades_df.at[i, "ID_LATTES"] = registro["ID_LATTES_NORMALIZADO"]

    if not entidades_df.at[i, "ORCID"]:
        entidades_df.at[i, "ORCID"] = registro["ORCID_NORMALIZADO"]

"""## 16. Reconciliação por identificadores

Depois do primeiro agrupamento, fazemos uma segunda verificação.

A finalidade é encontrar situações em que dois registros possuem o mesmo `ID_Lattes` ou ORCID, mas foram inicialmente separados.

Essa etapa funciona como uma validação da consistência do agrupamento.
"""

duplicados_lattes = (
    entidades_df[
        entidades_df["ID_LATTES"].notna() &
        (entidades_df["ID_LATTES"] != "")
    ]
    .groupby("ID_LATTES")["ID_ENTIDADE"]
    .nunique()
)

duplicados_lattes = duplicados_lattes[duplicados_lattes > 1]

duplicados_orcid = (
    entidades_df[
        entidades_df["ORCID"].notna() &
        (entidades_df["ORCID"] != "")
    ]
    .groupby("ORCID")["ID_ENTIDADE"]
    .nunique()
)

duplicados_orcid = duplicados_orcid[duplicados_orcid > 1]

print("Lattes associados a múltiplas entidades:")
display(duplicados_lattes)

print("ORCID associados a múltiplas entidades:")
display(duplicados_orcid)

"""## 17. Identificação de registros para revisão manual

Nem toda correspondência deve ser decidida automaticamente.

São enviados para revisão os casos que apresentam:

- conflito entre identificadores;
- nomes muito semelhantes, mas sem identificador suficiente;
- possíveis homônimos;
- outras situações que exigem validação humana.

A revisão manual é parte do método, e não um erro do sistema.

Em desambiguação de entidades, preservar a incerteza é melhor do que criar uma associação incorreta.
"""

# candidatos por similaridade para revisão
entidades_atual = entidades_df.copy()

candidatos = []

for _, registro in registros.iterrows():

    nome = registro["NOME_NORMALIZADO"]

    if not nome:
        continue

    for _, entidade in entidades_atual.iterrows():

        if registro["ID_LATTES_NORMALIZADO"] and            registro["ID_LATTES_NORMALIZADO"] == entidade["ID_LATTES"]:
            continue

        if registro["ORCID_NORMALIZADO"] and            registro["ORCID_NORMALIZADO"] == entidade["ORCID"]:
            continue

        score = similaridade_nomes(
            nome,
            entidade["NOME_NORMALIZADO"]
        )

        if 75 <= score < 95:
            candidatos.append({
                "ID_REGISTRO": registro["ID_REGISTRO"],
                "NOME_REGISTRO": registro["NOME_ORIGINAL"],
                "ID_ENTIDADE_CANDIDATA": entidade["ID_ENTIDADE"],
                "NOME_ENTIDADE_CANDIDATA": entidade["NOME_CANONICO"],
                "SCORE_NOME": score,
                "DECISAO": ""
            })

revisao_manual = pd.DataFrame(candidatos)

print("Candidatos para revisão:", len(revisao_manual))
display(revisao_manual.head(20))

"""## 18. Base integrada

Agora adicionamos o `ID_ENTIDADE` aos registros originais.

Esse é o ponto fundamental da integração.

Antes:

```text
OpenAlex → Ana Júlia...
Crossref → Ana Júlia...
```

Depois:

```text
OpenAlex  → ENT000001
Crossref  → ENT000001
```

O nome deixa de ser a principal chave de relacionamento.

O identificador interno do projeto passa a ser `ID_ENTIDADE`.
"""

base_integrada = registros.merge(
    mapa_registros[
        [
            "ID_REGISTRO",
            "ID_ENTIDADE",
            "METODO",
            "SCORE_NOME",
            "STATUS"
        ]
    ],
    on="ID_REGISTRO",
    how="left"
)

print("Base integrada:", base_integrada.shape)
display(base_integrada.head())

"""## 19. Separação das publicações por fonte

A base integrada ainda contém registros das duas fontes.

Para facilitar as etapas seguintes, criamos duas tabelas:

### OpenAlex

Relaciona:

```text
ID_ENTIDADE → publicação OpenAlex
```

### Crossref

Relaciona:

```text
ID_ENTIDADE → publicação Crossref
```

Essa separação preserva a estrutura original de cada fonte sem perder a chave comum.
"""

publicacoes_openalex = base_integrada[
    base_integrada["FONTE"] == "OpenAlex"
].copy()

publicacoes_crossref = base_integrada[
    base_integrada["FONTE"] == "Crossref"
].copy()

print("Publicações OpenAlex:", len(publicacoes_openalex))
print("Publicações Crossref:", len(publicacoes_crossref))

"""## 20. Indicadores de qualidade da desambiguação

Antes de considerar o módulo concluído, precisamos medir o resultado.

Os indicadores básicos são:

- quantidade de registros processados;
- quantidade de entidades criadas;
- correspondências automáticas;
- registros enviados para revisão;
- registros sem identificadores;
- possíveis conflitos de identificadores.

Esses indicadores permitem acompanhar a qualidade do processo e justificar metodologicamente as decisões.
"""

resumo = pd.DataFrame({
    "INDICADOR": [
        "Registros processados",
        "Entidades identificadas",
        "Correspondências automáticas",
        "Registros para revisão manual",
        "Novas entidades",
        "Conflitos de identificadores"
    ],
    "QUANTIDADE": [
        len(base_integrada),
        len(entidades_df),
        int((mapa_registros["STATUS"] == "AUTOMATICO").sum()),
        int((mapa_registros["STATUS"] == "REVISAO_MANUAL").sum()),
        int((mapa_registros["STATUS"] == "NOVA_ENTIDADE").sum()),
        int((mapa_registros["METODO"] == "REVISAO_MANUAL").sum())
    ]
})

display(resumo)

"""## 21. Exportação dos resultados

O módulo gera quatro produtos principais.

### `01_entidades.xlsx`

Cadastro mestre das pessoas identificadas.

### `02_mapa_registros.xlsx`

Mostra como cada registro de origem foi associado a uma entidade.

### `03_base_integrada.xlsx`

Base operacional contendo os dados das fontes e o `ID_ENTIDADE`.

### `04_revisao_manual.xlsx`

Casos que precisam de validação humana.

A separação desses produtos mantém a rastreabilidade entre **fonte → registro → entidade → publicação**.
"""

ARQUIVO_ENTIDADES = PASTA_SAIDA / "01_entidades.xlsx"
ARQUIVO_MAPA = PASTA_SAIDA / "02_mapa_registros.xlsx"
ARQUIVO_BASE = PASTA_SAIDA / "03_base_integrada.xlsx"
ARQUIVO_REVISAO = PASTA_SAIDA / "04_revisao_manual.xlsx"
ARQUIVO_RESUMO = PASTA_SAIDA / "05_resumo_qualidade.xlsx"

entidades_df.to_excel(ARQUIVO_ENTIDADES, index=False)
mapa_registros.to_excel(ARQUIVO_MAPA, index=False)
base_integrada.to_excel(ARQUIVO_BASE, index=False)
revisao_manual.to_excel(ARQUIVO_REVISAO, index=False)
resumo.to_excel(ARQUIVO_RESUMO, index=False)

print("Arquivos salvos em:")
print(PASTA_SAIDA)

"""## 22. Validação final

O módulo está conceitualmente concluído quando conseguimos responder às seguintes perguntas:

### Identidade

**Cada egresso possui um `ID_ENTIDADE`?**

### Rastreabilidade

**É possível saber de qual fonte veio cada registro?**

### Integração

**É possível encontrar todas as publicações de uma entidade?**

### Consistência

**Um mesmo `ID_Lattes` ou ORCID aparece associado a entidades diferentes?**

### Incerteza

**Os casos duvidosos estão separados para revisão?**

### Preservação

**Os dados originais continuam disponíveis?**

Se essas condições forem atendidas, a etapa de normalização e desambiguação pode alimentar os módulos posteriores de PLN, análise de produção científica e dashboard.

## 23. Como este módulo se conecta ao restante do projeto

O resultado deste notebook funciona como uma **camada de integração de identidade**.

```text
┌───────────────────────────────┐
│       FONTES DE DADOS         │
│                               │
│ Lattes | ORCID | OpenAlex     │
│ Crossref | LinkedIn           │
└──────────────┬────────────────┘
               ↓
┌───────────────────────────────┐
│ NORMALIZAÇÃO                   │
│ nomes + identificadores        │
└──────────────┬────────────────┘
               ↓
┌───────────────────────────────┐
│ DESAMBIGUAÇÃO                  │
│ comparação + evidências        │
└──────────────┬────────────────┘
               ↓
┌───────────────────────────────┐
│ ID_ENTIDADE                    │
│ identidade única do egresso    │
└──────────────┬────────────────┘
               ↓
┌───────────────────────────────┐
│ DADOS INTEGRADOS               │
│ formação + publicações +       │
│ atuação profissional           │
└──────────────┬────────────────┘
               ↓
┌───────────────────────────────┐
│ PLN / IA                       │
│ similaridade + temas + ODS     │
└──────────────┬────────────────┘
               ↓
┌───────────────────────────────┐
│ INDICADORES E DASHBOARD        │
└───────────────────────────────┘
```

### Conclusão

O objetivo desta etapa é estabelecer uma **identidade confiável e rastreável para cada egresso**, permitindo que os dados coletados em diferentes fontes sejam relacionados posteriormente.

O `ID_ENTIDADE` passa a funcionar como a chave lógica que conecta as diferentes dimensões do projeto.

> **Fonte → Registro → Entidade → Informação integrada → Indicador**

Essa separação é fundamental para que as análises posteriores não confundam homônimos nem contabilizem a mesma pessoa como indivíduos diferentes.
"""